Repository openfun/richie, pull requests merged in 2018-05, with the labels that each got.

#108 🐛(front) fix SearchFilter component prop typing naming
  richie/js/components/searchFilter/searchFilter.tsx
Labels: improvement, needs review

#109 Clean up resource list params in reducer
  richie/js/components/courseGlimpseListContainer/courseGlimpseListContainer.spec.tsx
  richie/js/components/searchFilterGroupContainer/searchFilterGroupContainer.spec.tsx
  richie/js/data/genericReducers/resourceList/resourceList.spec.ts
  richie/js/data/genericReducers/resourceList/resourceList.ts
  richie/js/data/genericSideEffects/getResourceList/actions.ts
  richie/js/settings.d.ts
  richie/js/settings.json
  richie/js/types/api.ts
Labels: feature, improvement, needs review

#104 🔧(gunicorn) redirect logs to stdout
  docker/files/usr/local/etc/gunicorn/richie.py
Labels: improvement, needs review

#137 🔥(news) Remove Newsblog dependency
  requirements/base.txt
  richie/settings.py
  richie/templates/aldryn_newsblog/article_detail.html
  richie/templates/aldryn_newsblog/article_list.html
  richie/templates/aldryn_newsblog/base.html
  richie/templates/aldryn_newsblog/includes/article.html
  richie/templates/aldryn_newsblog/includes/article_detail_view.html
  richie/templates/aldryn_newsblog/includes/pagination.html
  richie/templates/aldryn_newsblog/plugins/categories.html
  richie/templates/aldryn_newsblog/plugins/related_articles.html
Labels: needs review
