Repository openfun/richie, pull requests merged in 2018-07, with the labels that each got.

#270 🐛(settings) fix ES_INDEXES paths
  sandbox/settings.py
Labels: bug, critical

#262 ⬆️(dependencies) update npm dependencies
  package.json
  src/richie-front/js/components/CourseGlimpseListContainer/CourseGlimpseListContainer.tsx
  src/richie-front/js/components/SearchFilterGroupContainer/SearchFilterGroupContainer.tsx
  src/richie-front/js/components/SearchSuggestFieldContainer/SearchSuggestFieldContainer.tsx
  src/richie-front/js/integration_tests/filters.spec.tsx
  src/richie-front/js/utils/filters/updateFilter.ts
  yarn.lock
Labels: dependencies, needs review

#275 📌(pyup) restore dependency contraints
  setup.cfg
Labels: bug, dependencies, needs review

#277 ♻️(settings) move from JSON settings to TS settings
  src/richie-front/js/bootstrap.ts
  src/richie-front/js/components/SearchFilterGroupContainer/SearchFilterGroupContainer.tsx
  src/richie-front/js/components/SearchFiltersPane/SearchFiltersPane.tsx
  src/richie-front/js/components/SearchSuggestFieldContainer/SearchSuggestFieldContainer.tsx
  src/richie-front/js/data/filterDefinitions/reducer.ts
  src/richie-front/js/data/genericReducers/resourceList/resourceList.ts
  src/richie-front/js/data/genericSideEffects/getResourceList/getResourceList.ts
  src/richie-front/js/settings.json
  src/richie-front/js/settings.ts
  src/richie-front/js/utils/searchSuggest/getSuggestionsSection.ts
  webpack.config.js
Labels: easy pick, improvement, needs review

#284 🐳(compose) fix permissions for data directory
  Makefile
Labels: bug, needs review

#286 🐳(user) use an un-privileged user in tests
  .circleci/config.yml
  docker/compose/ci/docker-compose.yml
  docker/compose/test/docker-compose.yml
  docker/images/dev/Dockerfile
Labels: improvement

#306 🐛(pypi) fix package upload from the CI
  .circleci/config.yml
Labels: bug, needs review

#288 ✅(tests) Improve course test on html
  src/richie/apps/core/tests/utils.py
  src/richie/apps/courses/templates/courses/cms/course_detail.html
  tests/apps/courses/test_templates_course_detail.py
  tests/plugins/section/test_plugin.py
Labels: FUN, improvement

#315 Improve logging in the app container
  env.d/development
Labels: bug

#316 🐛(docker) use local user ID in the dev image
  Makefile
  docker/images/dev/Dockerfile
Labels: FUN, bug, needs review
