Repository openfun/richie, pull requests merged in 2018-06, with the labels that each got.

#173 (cms) Replace obsolet image plugin cmsplugin-filer by djangocms-picture
  requirements/base.txt
  richie/settings.py
Labels: needs review

#183 Upgrade js deps
  package.json
  yarn.lock
Labels: needs review

#188 🐛(circle) fix yarn.lock file update
  .circleci/config.yml
Labels: bug

#190 Update package.json description, license and author
  package.json
Labels: improvement

#196 Add gitlint to enforce format of commit messages
  .circleci/config.yml
  .gitlint
  gitlint/gitlint_emoji.py
Labels: FUN, improvement

#201 🐛(circle) force lockfile-front as the first job
  .circleci/config.yml
Labels: FUN, bug, needs review

#203 💚(gitlint) ignore bots git message lint
  .gitlint
Labels: improvement, needs review

#211 🚸(gitlint) Improve UC1 error message
  gitlint/gitlint_emoji.py
Labels: needs review

#227 ⬆️(package) upgrade front-end dependencies
  package.json
  yarn.lock
Labels: greenkeeper

#241 Make pyup less noisy
  .pyup.yml
Labels: FUN, improvement, needs review

#31 Add cache invalidation mechanism for js/css files
  richie/settings.py
Labels: improvement, needs review
