Repository openfun/richie, pull requests merged in 2018-04, with the labels that each got.

#75 👷(circle) move to a richie's container based CI
  .circleci/config.yml
  docker/compose/ci/docker-compose.yml
  docker/images/alpine/dev/Dockerfile
  docker/images/dev/Dockerfile
  env.d/ci
Labels: feature

#94 Fix an issue on org & subject filters on course search
  apps/search/tests/test_viewsets_course.py
  apps/search/viewsets/course.py
Labels: bug

#96 Update configurations to run Richie on OpenShift
  richie/settings.py
Labels: enhancement

#100 💚(circle) fix dev images cache & hub job
  .circleci/config.yml
Labels: critical
