Repository openfun/richie, pull requests merged in 2019-11, with the labels that each got.

#890 📝(frontend) document the <UserLogin /> component
  docs/django-react-interop.md
Labels: docs website, needs review

#887 📝(website) document the frontend build for dependents
  docs/building-the-frontend.md
  website/sidebars.json
Labels: docs website, needs help, needs review

#896 ♻️(frontend) remove act warnings in <Search />
  src/frontend/js/components/Search/index.spec.tsx
Labels: improvement, needs review

#889 Fix logo link in base footer
  src/richie/apps/core/templates/richie/base.html
Labels: bug, improvement

#908 🔖(chore) bump version to 1.14.0
  CHANGELOG.md
  setup.cfg
  src/frontend/js/translations/fr-CA.json
  src/frontend/js/translations/fr-FR.json
  src/frontend/package.json
  src/richie/locale/fr_FR/LC_MESSAGES/django.mo
  src/richie/locale/fr_FR/LC_MESSAGES/django.po
  website/package.json
  website/versioned_docs/version-1.14/django-react-interop.md
  website/versions.json
Labels: bug, improvement

#909 🐛(courses) add migrate dependency to update section b4 creating footer
  CHANGELOG.md
  src/richie/apps/courses/migrations/0010_auto_footer_to_static_placeholder.py
Labels: bug

#910 🔖(chore) bump version to 1.14.1
  CHANGELOG.md
  setup.cfg
  src/frontend/package.json
  website/package.json
Labels: bug, critical

#911 📝(upgrade) add missing instructions for user related urls and settings
  UPGRADE.md
Labels: bug, critical

#914 🌐(frontend) do not report errors related to en-US l10n files
  src/frontend/js/index.tsx
Labels: improvement, needs review
