Repository openfun/richie, pull requests merged in 2019-03, with the labels that each got.

#511 💄(homepage) improve homepage layout
  sandbox/settings.py
  src/frontend/scss/_colors.scss
  src/frontend/scss/_main.scss
  src/frontend/scss/_variables.scss
  src/frontend/scss/mixins/_hero.scss
  src/richie/apps/core/management/commands/create_demo_site.py
  src/richie/plugins/large_banner/templates/richie/large_banner/_hero-intro.scss
  src/richie/plugins/large_banner/templates/richie/large_banner/hero-intro.html
  src/richie/plugins/section/templates/richie/section/_highlighted_items.scss
  src/richie/plugins/section/templates/richie/section/highlighted_items.html
Labels: improvement

#518 💄(homepage) add homepage plugin constraints and enable LinkPlugin
  sandbox/settings.py
  sandbox/templates/djangocms_link/button-caesura/link.html
  src/richie/plugins/section/templates/richie/section/_highlighted_items.scss
Labels: improvement

#519 💄(project) add new template for a simple single column page
  sandbox/settings.py
  sandbox/templates/richie/_single-column.scss
  sandbox/templates/richie/single-column.html
  src/frontend/scss/_main.scss
Labels: improvement

#520 💄(homepage) enable PersonPlugin on homepage sections
  sandbox/settings.py
  src/richie/apps/core/management/commands/create_demo_site.py
  src/richie/plugins/section/templates/richie/section/_highlighted_items.scss
  src/richie/plugins/section/templates/richie/section/highlighted_items.html
Labels: improvement

#521 🔧(project) disable some unused cms plugins
  sandbox/settings.py
  setup.cfg
Labels: dependencies, improvement, question

#522 🔧(single-column) proper placeholder config for single column template
  sandbox/settings.py
Labels: easy pick, improvement

#526 Bump release to 1.0.0-beta.2
  CHANGELOG.md
  setup.cfg
  src/frontend/package.json
Labels: FUN

#528 🔥(sandbox) cleaned up every templates and statics from sandbox
  sandbox/static/css/main.css
  sandbox/static/images/homepage1280.jpg
  sandbox/static/images/homepage1900.jpg
  sandbox/static/images/homepage2495.jpg
  sandbox/static/images/homepage768.jpg
  sandbox/static/images/icones/calendar-red.png
  sandbox/static/images/icones/folder-red.png
  sandbox/static/images/icones/social-networks-hover.png
  sandbox/static/images/icones/social-networks.png
  sandbox/static/images/icones/star-red.png
  sandbox/static/images/samples/main-organization.png
  src/frontend/scss/_main.scss
  src/richie/apps/core/static/images/logo.png
  src/richie/apps/core/templates/cms/plugins/text.html
  src/richie/apps/core/templates/djangocms_link/button-caesura/link.html
  src/richie/apps/core/templates/djangocms_video/full-width/video_player.html
  src/richie/apps/core/templates/menu/_menu.scss
  src/richie/apps/core/templates/menu/footer_menu.html
  src/richie/apps/core/templates/menu/header_menu.html
  src/richie/apps/core/templates/menu/menu.html
  src/richie/apps/core/templates/richie/_single-column.scss
  src/richie/apps/core/templates/richie/base.html
  src/richie/apps/core/templates/richie/child_pages_list.html
  src/richie/apps/core/templates/richie/fullwidth.html
  src/richie/apps/core/templates/richie/homepage.html
  src/richie/apps/core/templates/richie/single-column.html
Labels: improvement

#514 ✨(search) show nested filter values (lv. 1) in the search filters pane
  src/frontend/js/components/SearchFilter/SearchFilter.spec.tsx
  src/frontend/js/components/SearchFilter/SearchFilter.tsx
  src/frontend/js/components/SearchFilter/_SearchFilter.scss
  src/frontend/js/components/SearchFilterGroup/SearchFilterGroup.spec.tsx
  src/frontend/js/components/SearchFilterGroup/SearchFilterGroup.tsx
  src/frontend/js/components/SearchFilterValueLeaf/SearchFilterValueLeaf.spec.tsx
  src/frontend/js/components/SearchFilterValueLeaf/SearchFilterValueLeaf.tsx
  src/frontend/js/components/SearchFilterValueParent/SearchFilterValueParent.spec.tsx
  src/frontend/js/components/SearchFilterValueParent/SearchFilterValueParent.tsx
  src/frontend/js/data/useFilterValue/useFilterValue.spec.tsx
  src/frontend/js/data/useFilterValue/useFilterValue.ts
  src/frontend/js/types/filters.ts
  src/frontend/scss/_main.scss
  src/frontend/scss/objects/_search-filter-value.scss
Labels: feature, needs review

#531 🐛(courses) add missing migrations on courses
  src/richie/apps/courses/migrations/0001_initial.py
Labels: bug

#533 🔖(chore) bump release to 1.0.0-beta.3
  CHANGELOG.md
  setup.cfg
  src/frontend/package.json
Labels: FUN, needs review

#534 🐛(sandbox) remove STATICFILES_DIRS setting
  CHANGELOG.md
  sandbox/settings.py
Labels: bug, critical, needs review

#535 🚚(core) rename cover fixtures to standardized filename
  src/richie/apps/core/fixtures/cover/cover1.jpg
  src/richie/apps/core/fixtures/cover/cover2.jpg
  src/richie/apps/core/fixtures/cover/cover3.jpg
Labels: easy pick, improvement

#536 🐛(course) fix cover fixture for course factory
  src/richie/apps/courses/factories.py
Labels: bug

#545 🐛(courses) define availability as a drilldown filter
  src/richie/apps/search/defaults.py
  tests/apps/search/test_query_courses.py
  tests/apps/search/test_viewsets_courses.py
Labels: bug, easy pick

#546 🐛(search) exclude snapshots from the courses index
  src/richie/apps/search/indexers/courses.py
  tests/apps/search/test_indexers_courses.py
Labels: bug, easy pick

#548 🐛(project) fix watch-sass for sources out of frontend directory
  src/frontend/package.json
Labels: bug

#532 ✨(blog) add Blog post
  sandbox/settings.py
  src/frontend/package.json
  src/frontend/scss/_main.scss
  src/frontend/scss/objects/_blogpost_glimpses.scss
  src/frontend/scss/objects/_course_glimpses.scss
  src/richie/apps/core/management/commands/create_demo_site.py
  src/richie/apps/courses/cms_plugins.py
  src/richie/apps/courses/cms_wizards.py
  src/richie/apps/courses/factories.py
  src/richie/apps/courses/migrations/0001_initial.py
  src/richie/apps/courses/models/__init__.py
  src/richie/apps/courses/models/blog.py
  src/richie/apps/courses/models/category.py
  src/richie/apps/courses/templates/courses/cms/_blogpost_detail.scss
  src/richie/apps/courses/templates/courses/cms/blogpost_detail.html
  src/richie/apps/courses/templates/courses/cms/blogpost_list.html
  src/richie/apps/courses/templates/courses/cms/category_detail.html
  src/richie/apps/courses/templates/courses/cms/fragment_blogpost_glimpse.html
  src/richie/apps/courses/templates/courses/plugins/_blogpost_plugin.scss
  src/richie/apps/courses/templates/courses/plugins/blogpost.html
  src/richie/apps/persons/templates/persons/plugins/person.html
  src/richie/plugins/section/templates/richie/section/_highlighted_items.scss
  tests/apps/courses/test_cms_plugins_blogpost.py
  tests/apps/courses/test_cms_wizards_blogpost.py
  tests/apps/courses/test_factories_blogpost.py
  tests/apps/courses/test_models_blogpost.py
  tests/apps/courses/test_models_category.py
  tests/apps/courses/test_templates_blogpost_detail.py
Labels: improvement

#549 💄(course) fix minor feedbacks for layout reported in #540
  src/frontend/js/components/SearchFiltersPane/_SearchFiltersPane.scss
  src/richie/apps/courses/templates/courses/cms/_course_detail.scss
Labels: easy pick, improvement

#557 🐛(search) improve caching of include regex on indexable filters
  src/richie/apps/search/filter_definitions/courses.py
  tests/apps/search/test_filter_definitions.py
  tests/apps/search/test_query_courses.py
Labels: FUN, bug

#509 🐛(category) fix duplicate category
  src/richie/apps/courses/models/category.py
  src/richie/apps/courses/models/course.py
  src/richie/apps/courses/models/organization.py
  tests/apps/courses/test_cms_plugins_category.py
  tests/apps/courses/test_cms_plugins_course.py
  tests/apps/courses/test_cms_plugins_organization.py
Labels: bug

#559 📝(readme) add link to demo site, remove exclusive reference to Open edX
  README.md
Labels: easy pick, feature

#560 💄(project) change logo to a generic one
  src/richie/apps/core/static/images/logo.png
Labels: improvement

#558 🐛(search) make sure selected filter values are included in the result
  src/richie/apps/search/filter_definitions/courses.py
  src/richie/apps/search/filter_definitions/mixins.py
  tests/apps/search/test_filter_definitions.py
  tests/apps/search/test_query_courses.py
  tests/apps/search/test_query_courses_edge_cases.py
Labels: FUN, bug, critical

#571 ✨(project) add new context processor to add Site values in templates
  sandbox/settings.py
  src/richie/apps/core/context_processors.py
  src/richie/apps/core/templates/richie/base.html
Labels: improvement

#564 ✨(social-badges) add social network badges template snippets
  src/frontend/scss/_main.scss
  src/frontend/scss/components/_footer.scss
  src/frontend/scss/templates/core/social-networks/_social-networks.scss
  src/frontend/scss/templates/courses/cms/_blogpost_detail.scss
  src/frontend/scss/templates/courses/cms/_course_detail.scss
  src/frontend/scss/vendor/_icomoon.scss
  src/richie/apps/core/static/fonts/icomoon/icomoon.eot
  src/richie/apps/core/static/fonts/icomoon/icomoon.svg
  src/richie/apps/core/static/fonts/icomoon/icomoon.ttf
  src/richie/apps/core/static/fonts/icomoon/icomoon.woff
  src/richie/apps/core/static/fonts/icomoon/selection.json
  src/richie/apps/core/templates/richie/base.html
  src/richie/apps/core/templates/social-networks/blogpost-badges.html
  src/richie/apps/core/templates/social-networks/course-badges.html
  src/richie/apps/core/templates/social-networks/footer-badges.html
  src/richie/apps/courses/templates/courses/cms/blogpost_detail.html
  src/richie/apps/courses/templates/courses/cms/course_detail.html
Labels: improvement

#552 ✨(menu) add language chooser menu
  src/frontend/scss/components/_header.scss
  src/richie/apps/core/templates/menu/language_menu.html
  src/richie/apps/core/templates/richie/base.html
  tests/apps/core/test_language_chooser.py
Labels: feature
