Repository openfun/richie, pull requests merged in 2019-12, with the labels that each got.

#917 🔖(chore) bump version to 1.15.0
  CHANGELOG.md
  UPGRADE.md
  setup.cfg
  src/frontend/package.json
  website/package.json
  website/versioned_docs/version-1.15/django-react-interop.md
  website/versions.json
Labels: improvement

#922 📌(backend) pin Django to less than 3.0
  CHANGELOG.md
  setup.cfg
Labels: bug

#924 ⬆️(dependencies) update npm dependencies
  src/frontend/package.json
  src/frontend/yarn.lock
Labels: dependencies

#925 🔖(chore) bump version to 1.16.0
  CHANGELOG.md
  setup.cfg
  src/frontend/js/translations/fr-CA.json
  src/frontend/js/translations/fr-CA.po
  src/frontend/js/translations/fr-FR.json
  src/frontend/js/translations/fr-FR.po
  src/frontend/package.json
  src/richie/apps/courses/templates/courses/cms/fragment_course_run.html
  src/richie/apps/courses/templates/courses/cms/fragment_course_runs_list.html
  src/richie/locale/fr_CA/LC_MESSAGES/django.mo
  src/richie/locale/fr_CA/LC_MESSAGES/django.po
  src/richie/locale/fr_FR/LC_MESSAGES/django.mo
  src/richie/locale/fr_FR/LC_MESSAGES/django.po
  tests_e2e/package.json
  website/package.json
  website/versioned_docs/version-1.16/accessibility-testing.md
  website/versioned_docs/version-1.16/django-react-interop.md
  website/versioned_sidebars/version-1.16-sidebars.json
  website/versions.json
Labels: improvement

#927 🔧(courses) allow CKEditor on course format, prerequisite and assessment
  CHANGELOG.md
  src/richie/apps/courses/settings/__init__.py
Labels: improvement

#928 🔖(chore) bump version to 1.16.1
  CHANGELOG.md
  setup.cfg
  src/frontend/package.json
  tests_e2e/package.json
  website/package.json
Labels: improvement
