Repository openfun/richie, pull requests merged in 2019-07, with the labels that each got.

#749 🐛(courses) fix getting objects related to a course via plugins
  CHANGELOG.md
  src/richie/apps/courses/models/course.py
  tests/apps/courses/test_models_course.py
Labels: bug

#751 Don't keep stale user input when a suggestion is selected
  CHANGELOG.md
  src/frontend/js/components/SearchSuggestField/SearchSuggestField.spec.tsx
  src/frontend/js/components/SearchSuggestField/SearchSuggestField.tsx
Labels: bug, critical

#756 ✏️(scss) fix typo in variable name
  CHANGELOG.md
  src/frontend/scss/components/_header.scss
Labels: bug, needs review

#762 👷(linters) lint backend source code with bandit
  .circleci/config.yml
  CHANGELOG.md
  Makefile
  setup.cfg
  src/richie/apps/core/factories.py
  src/richie/apps/core/helpers.py
  src/richie/apps/courses/factories.py
  src/richie/apps/courses/helpers.py
  src/richie/apps/demo/management/commands/create_demo_site.py
  src/richie/apps/demo/utils.py
  tests/apps/core/test_helpers.py
  tests/apps/courses/test_admin_page_snapshot.py
Labels: improvement

#765 🔖(chore) bump version to 1.5.2
  CHANGELOG.md
  setup.cfg
  src/frontend/package.json
Labels: improvement

#767 Add settings for facet limits
  src/richie/apps/search/defaults.py
  src/richie/apps/search/filter_definitions/courses.py
  src/richie/apps/search/filter_definitions/mixins.py
  tests/apps/search/test_query_courses_facet_limits.py
Labels: bug, feature, needs review

#770 🔖(chore) bump version to 1.6.0
  CHANGELOG.md
  setup.cfg
  src/frontend/package.json
Labels: improvement
