Repository openfun/richie, pull requests merged in 2019-02, with the labels that each got.

#469 🔖(chore) bump release to 1.0.0-beta.1
  CHANGELOG.md
  package.json
  setup.cfg
Labels: FUN, needs review

#470 ⬆️(sentry) move from raven to sentry SDK
  sandbox/settings.py
  sandbox/wsgi.py
  setup.cfg
  tests/sandbox/test_settings.py
Labels: dependencies, improvement, needs review

#478 🐛(jobs) fix circle CI upload string with new file structure
  .circleci/config.yml
  scripts/i18n/upload.js
  scripts/package.json
  src/frontend/package.json
Labels: bug, needs review

#480 🐛(courserun) fix randomly failing tests linked to course run datetimes
  src/richie/apps/courses/factories.py
  tests/apps/courses/test_models_course_glimpse_date.py
Labels: FUN, bug, needs review

#481 🚚(courses) rename test_models_course_glimpse_date.py
  tests/apps/courses/test_models_course_state.py
Labels: FUN, improvement, needs review

#498 ✨(plugins) add 'template'field to Section plugin
  sandbox/settings.py
  sandbox/templates/richie/homepage.html
  src/richie/plugins/section/cms_plugins.py
  src/richie/plugins/section/defaults.py
  src/richie/plugins/section/factories.py
  src/richie/plugins/section/migrations/0002_add_template_field.py
  src/richie/plugins/section/models.py
Labels: improvement

#497 ✨(plugins) add 'template' and 'content' field to LargeBanner plugin
  sandbox/settings.py
  src/frontend/scss/_main.scss
  src/richie/plugins/large_banner/cms_plugins.py
  src/richie/plugins/large_banner/defaults.py
  src/richie/plugins/large_banner/factories.py
  src/richie/plugins/large_banner/forms.py
  src/richie/plugins/large_banner/migrations/0002_add_template_and_content_fields.py
  src/richie/plugins/large_banner/migrations/0003_make_logo_optional.py
  src/richie/plugins/large_banner/models.py
  src/richie/plugins/large_banner/templates/richie/large_banner/_large_banner.scss
  src/richie/plugins/large_banner/templates/richie/large_banner/large_banner.html
  tests/plugins/large_banner/test_cms_plugins.py
Labels: improvement
