Repository openfun/richie, pull requests merged in 2019-08, with the labels that each got.

#772 Move the search template title into react
  CHANGELOG.md
  src/frontend/js/components/Search/Search.tsx
  src/frontend/js/components/Search/_Search.scss
  src/frontend/js/index.tsx
  src/frontend/scss/templates/search/_search.scss
  src/richie/apps/search/templates/search/search.html
  tests/apps/search/test_templates_search.py
Labels: improvement

#773 💄(fonts) change richie's font to "Exo 2"
  CHANGELOG.md
  src/frontend/scss/_fonts.scss
  src/frontend/scss/_main.scss
  src/richie/apps/core/static/fonts/exo2-bold-webfont.woff
  src/richie/apps/core/static/fonts/exo2-bold-webfont.woff2
  src/richie/apps/core/static/fonts/exo2-bolditalic-webfont.woff
  src/richie/apps/core/static/fonts/exo2-bolditalic-webfont.woff2
  src/richie/apps/core/static/fonts/exo2-medium-webfont.woff
  src/richie/apps/core/static/fonts/exo2-medium-webfont.woff2
  src/richie/apps/core/static/fonts/exo2-mediumitalic-webfont.woff
  src/richie/apps/core/static/fonts/exo2-mediumitalic-webfont.woff2
Labels: easy pick

#782 ✨(search) make autosuggestion diacritics insensitive
  CHANGELOG.md
  src/richie/apps/search/index_manager.py
  src/richie/apps/search/indexers/categories.py
  src/richie/apps/search/indexers/courses.py
  src/richie/apps/search/indexers/organizations.py
  src/richie/apps/search/indexers/persons.py
  src/richie/apps/search/text_indexing.py
  tests/apps/search/test_autocomplete_categories.py
  tests/apps/search/test_autocomplete_courses.py
  tests/apps/search/test_autocomplete_organizations.py
  tests/apps/search/test_autocomplete_persons.py
Labels: feature, improvement, needs review

#784 ✨(courses) allow icons to display on course detail and not on glimpse
  CHANGELOG.md
  src/frontend/scss/templates/courses/cms/_course_detail.scss
  src/frontend/scss/templates/courses/plugins/_category_plugin.scss
  src/richie/apps/courses/factories.py
  src/richie/apps/courses/settings/__init__.py
  src/richie/apps/courses/templates/courses/cms/course_detail.html
  src/richie/apps/courses/templates/courses/plugins/category_plugin.html
  src/richie/apps/demo/defaults.py
  src/richie/apps/demo/helpers.py
  tests/apps/courses/test_factories_category.py
  tests/apps/courses/test_templates_blogpost_detail.py
  tests/apps/courses/test_templates_course_detail.py
  tests/apps/courses/test_templates_course_run_detail.py
  tests/apps/courses/test_templates_person_detail.py
Labels: feature

#788 🐛(project) add woff2 in manifest for newly added font
  MANIFEST.in
Labels: bug, critical

#789 🔖(chore) bump version to 1.7.1
  CHANGELOG.md
  setup.cfg
  src/frontend/package.json
Labels: bug, critical

#794 🐛(project) change location of core static files so fonts can be found
  CHANGELOG.md
  src/frontend/scss/_fonts.scss
  src/frontend/scss/vendor/_icomoon.scss
  src/richie/apps/core/static/richie/fonts/exo2-bold-webfont.woff
  src/richie/apps/core/static/richie/fonts/exo2-bold-webfont.woff2
  src/richie/apps/core/static/richie/fonts/exo2-bolditalic-webfont.woff
  src/richie/apps/core/static/richie/fonts/exo2-bolditalic-webfont.woff2
  src/richie/apps/core/static/richie/fonts/exo2-medium-webfont.woff
  src/richie/apps/core/static/richie/fonts/exo2-medium-webfont.woff2
  src/richie/apps/core/static/richie/fonts/exo2-mediumitalic-webfont.woff
  src/richie/apps/core/static/richie/fonts/exo2-mediumitalic-webfont.woff2
  src/richie/apps/core/static/richie/fonts/icomoon/icomoon.eot
  src/richie/apps/core/static/richie/fonts/icomoon/icomoon.svg
  src/richie/apps/core/static/richie/fonts/icomoon/icomoon.ttf
  src/richie/apps/core/static/richie/fonts/icomoon/icomoon.woff
  src/richie/apps/core/static/richie/fonts/icomoon/selection.json
  src/richie/apps/core/static/richie/images/logo.png
  src/richie/apps/core/templates/richie/base.html
Labels: bug

#797 🐛(project) fix logo url in footer
  CHANGELOG.md
  src/richie/apps/core/templates/richie/base.html
Labels: bug

#798 Fix a template error in the person plugin
  CHANGELOG.md
  src/richie/apps/courses/templates/courses/plugins/person.html
  tests/apps/courses/test_templates_blogpost_detail.py
Labels: bug

#799 🔖(chore) bump version to 1.8.0
  CHANGELOG.md
  setup.cfg
  src/frontend/package.json
Labels: improvement

#801 Fix "more options" modal for non-mptt-paths based filters
  CHANGELOG.md
  src/frontend/js/components/SearchFilterGroupModal/index.spec.tsx
  src/frontend/js/components/SearchFilterGroupModal/index.tsx
Labels: bug

#802 Improve error messages in the "more options" modal in filters
  CHANGELOG.md
  src/frontend/js/components/SearchFilterGroupModal/_SearchFilterGroupModal.scss
  src/frontend/js/components/SearchFilterGroupModal/index.spec.tsx
  src/frontend/js/components/SearchFilterGroupModal/index.tsx
Labels: bug

#803 Improve a string in the blogpost detail template
  src/richie/apps/courses/templates/courses/cms/blogpost_detail.html
Labels: improvement, needs review

#806 Improve pagination UX in course search
  CHANGELOG.md
  src/frontend/js/components/PaginateCourseSearch/_PaginateCourseSearch.scss
  src/frontend/js/components/PaginateCourseSearch/index.tsx
Labels: improvement, needs review

#807 🔒(dependencies) bump set-value to > 2.0.1
  CHANGELOG.md
  src/frontend/yarn.lock
Labels: dependencies

#808 Improve and complete strings in pagination
  CHANGELOG.md
  src/frontend/js/components/PaginateCourseSearch/index.spec.tsx
  src/frontend/js/components/PaginateCourseSearch/index.tsx
Labels: bug, improvement
