Repository openfun/richie, pull requests merged in 2019-10, with the labels that each got.

#786 💄(glimpse) add template for organization plugin
  CHANGELOG.md
  src/richie/apps/courses/cms_plugins.py
  src/richie/apps/courses/defaults.py
  src/richie/apps/courses/migrations/0007_auto_20190930_2245.py
  src/richie/apps/courses/models/organization.py
  src/richie/apps/courses/templates/courses/cms/fragment_organization_glimpse.html
  src/richie/apps/courses/templates/courses/plugins/organization.html
  tests/apps/courses/test_cms_plugins_organization.py
  tests/apps/courses/test_templates_person_detail.py
Labels: feature, improvement, needs review

#850 🔖(chore) bump version to 1.10.0
  CHANGELOG.md
  setup.cfg
  src/frontend/package.json
Labels: bug, improvement

#854 🔖(chore) bump version to 1.11.0
  CHANGELOG.md
  setup.cfg
  src/frontend/package.json
Labels: feature

#855 ♿️(search) fix frontend pagination accessibility issue
  CHANGELOG.md
  src/frontend/js/components/PaginateCourseSearch/index.tsx
Labels: improvement

#860 🐛(sandbox) make API calls work behind an htaccess
  CHANGELOG.md
  sandbox/settings.py
  tests/sandbox/test_settings.py
Labels: bug

#863 👷(circleci) fix test-back-mysql following mysql image upgrade
  .circleci/config.yml
Labels: bug

#861 🐛(templates) fix bug in course detail
  src/frontend/scss/templates/courses/cms/_course_detail.scss
  src/richie/apps/courses/templates/courses/cms/course_detail.html
Labels: bug, critical

#868 🔖(chore) bump version to 1.12.0
  CHANGELOG.md
  setup.cfg
  src/frontend/package.json
Labels: FUN Team

#871 Fix documentation build on the CI
  .circleci/config.yml
Labels: bug, docs website

#872 🐛(website) fix documentation build [REVERT]
  .circleci/config.yml
Labels: docs website, improvement, needs review

#877 🐛(frontend) fix a 400 Bad Request issue in <RootSearchSuggestField />
  CHANGELOG.md
  src/frontend/js/components/RootSearchSuggestField/index.spec.tsx
  src/frontend/js/components/RootSearchSuggestField/index.tsx
Labels: bug, needs review
