Repository openfun/richie, pull requests merged in 2019-09, with the labels that each got.

#814 🐛(settings) allow overriding default settings defined in Richie's mixin
  CHANGELOG.md
  src/richie/apps/courses/settings/mixins.py
  tests/apps/courses/test_settings_mixins.py
Labels: bug

#816 🔖(chore) bump version to 1.8.3
  CHANGELOG.md
  setup.cfg
  src/frontend/package.json
Labels: bug

#820 🌐(core) translate login/signup on header
  CHANGELOG.md
  src/richie/apps/core/templates/richie/base.html
  src/richie/locale/fr_CA/LC_MESSAGES/django.mo
  src/richie/locale/fr_CA/LC_MESSAGES/django.po
  src/richie/locale/fr_FR/LC_MESSAGES/django.mo
  src/richie/locale/fr_FR/LC_MESSAGES/django.po
Labels: improvement, needs review

#821 ✨(layout) add breadcrumbs on top of page details
  CHANGELOG.md
  src/frontend/scss/_main.scss
  src/frontend/scss/objects/_breadcrumbs.scss
  src/richie/apps/core/templates/menu/breadcrumb_item.html
  src/richie/apps/core/templates/richie/base.html
  src/richie/apps/core/templates/richie/homepage.html
  src/richie/apps/courses/templates/courses/cms/blogpost_list.html
  src/richie/apps/courses/templates/courses/cms/category_list.html
  src/richie/apps/courses/templates/courses/cms/course_detail.html
  src/richie/apps/courses/templates/courses/cms/organization_list.html
  src/richie/apps/courses/templates/courses/cms/person_list.html
  src/richie/apps/search/templates/search/search.html
Labels: feature

#827 ⬆️ (circle) upgrade crowdin image version
  .circleci/config.yml
  CHANGELOG.md
Labels: FUN Team, improvement

#817 ✨(program) add program content, related to issue #544
  CHANGELOG.md
  src/frontend/scss/_main.scss
  src/frontend/scss/objects/_program_glimpses.scss
  src/frontend/scss/templates/courses/cms/_program_detail.scss
  src/richie/apps/courses/cms_plugins.py
  src/richie/apps/courses/cms_wizards.py
  src/richie/apps/courses/defaults.py
  src/richie/apps/courses/factories.py
  src/richie/apps/courses/migrations/0006_add_program.py
  src/richie/apps/courses/models/__init__.py
  src/richie/apps/courses/models/program.py
  src/richie/apps/courses/settings/__init__.py
  src/richie/apps/courses/templates/courses/cms/fragment_program_glimpse.html
  src/richie/apps/courses/templates/courses/cms/program_detail.html
  src/richie/apps/courses/templates/courses/cms/program_list.html
  src/richie/apps/courses/templates/courses/plugins/program.html
  src/richie/apps/demo/defaults.py
  src/richie/apps/demo/management/commands/create_demo_site.py
  tests/apps/core/test_helpers.py
  tests/apps/courses/test_cms_plugins_program.py
  tests/apps/courses/test_cms_wizards_program.py
  tests/apps/courses/test_factories_program.py
  tests/apps/courses/test_models_program.py
  tests/apps/courses/test_settings_mixins.py
  tests/apps/courses/test_templates_program_detail.py
  tests/apps/demo/test_commands_create_demo_site.py
Labels: feature

#647 🔍(SEO) configure meta and opengraph tags
  CHANGELOG.md
  src/richie/apps/core/templates/richie/base.html
  src/richie/apps/core/templates/richie/fullwidth.html
  src/richie/apps/core/templates/richie/homepage.html
  src/richie/apps/core/templates/richie/single_column.html
  src/richie/apps/courses/templates/courses/cms/blogpost_detail.html
  src/richie/apps/courses/templates/courses/cms/category_detail.html
  src/richie/apps/courses/templates/courses/cms/course_detail.html
  src/richie/apps/courses/templates/courses/cms/course_run_detail.html
  src/richie/apps/courses/templates/courses/cms/organization_detail.html
  src/richie/apps/courses/templates/courses/cms/person_detail.html
  src/richie/apps/courses/templates/courses/cms/program_detail.html
Labels: improvement

#830 🔖(chore) bump version to 1.9.0
  CHANGELOG.md
  setup.cfg
  src/frontend/package.json
Labels: FUN Team, improvement

#831 📝(project) add a file at the root of the project to document upgrades
  CHANGELOG.md
  UPGRADE.md
Labels: improvement

#834 🐛(static) fix logo location that breaks static finder
  src/richie/apps/core/templates/richie/base.html
Labels: bug, critical

#835 🔖(chore) bump version to 1.9.2
  CHANGELOG.md
  setup.cfg
  src/frontend/package.json
Labels: bug, critical

#833 Use SVG icons instead of an icon font
  CHANGELOG.md
  UPGRADE.md
  src/frontend/scss/_main.scss
  src/frontend/scss/_utils.scss
  src/frontend/scss/components/_footer.scss
  src/frontend/scss/templates/core/social-networks/_social-networks.scss
  src/frontend/scss/templates/courses/cms/_blogpost_detail.scss
  src/frontend/scss/templates/courses/cms/_course_detail.scss
  src/frontend/scss/vendor/_icomoon.scss
  src/richie/apps/core/static/richie/fonts/icomoon/icomoon.eot
  src/richie/apps/core/static/richie/fonts/icomoon/icomoon.svg
  src/richie/apps/core/static/richie/fonts/icomoon/icomoon.ttf
  src/richie/apps/core/static/richie/fonts/icomoon/icomoon.woff
  src/richie/apps/core/static/richie/fonts/icomoon/selection.json
  src/richie/apps/core/static/richie/icons.svg
  src/richie/apps/core/templates/social-networks/blogpost-badges.html
  src/richie/apps/core/templates/social-networks/course-badges.html
  src/richie/apps/core/templates/social-networks/footer-badges.html
  src/richie/apps/courses/templates/courses/cms/course_detail.html
Labels: improvement

#811 🐛(template) update fragment_course_content
  CHANGELOG.md
  src/richie/apps/courses/templates/courses/cms/fragment_course_content.html
  tests/apps/courses/test_templates_course_detail.py
Labels: bug, needs review

#836 💄(layout) enable submenu in footer main menu
  CHANGELOG.md
  src/frontend/scss/components/_footer.scss
  src/richie/apps/core/templates/menu/footer_menu.html
  src/richie/apps/core/templates/richie/base.html
Labels: improvement
