Repository openfun/richie, pull requests merged in 2019-06, with the labels that each got.

#719 🔧(sandbox) make X_FRAME_OPTIONS setting configurable
  sandbox/settings.py
Labels: improvement, needs review

#717 🐛(permissions) fix page permissions that were making pages private
  CHANGELOG.md
  src/richie/apps/courses/defaults.py
  tests/apps/courses/test_cms_wizards_course.py
  tests/apps/courses/test_cms_wizards_organization.py
Labels: bug

#721 🔖(chore) bump release to 1.0.1
  CHANGELOG.md
  setup.cfg
  src/frontend/package.json
Labels: bug

#722 🔖(chore) bump release to 1.1.0
  CHANGELOG.md
  setup.cfg
  src/frontend/package.json
Labels: FUN

#723 🚸(search) harmonize glimpse image size on search page
  CHANGELOG.md
  src/richie/apps/courses/settings/__init__.py
Labels: bug

#730 🔖(chore) bump release to 1.2.0
  CHANGELOG.md
  setup.cfg
  src/frontend/package.json
Labels: bug, feature

#731 ♻️(persons) replace firstname, lastname and person title by page title
  CHANGELOG.md
  src/richie/apps/courses/admin.py
  src/richie/apps/courses/cms_wizards.py
  src/richie/apps/courses/factories.py
  src/richie/apps/courses/migrations/0004_auto_20190619_1630.py
  src/richie/apps/courses/models/person.py
  src/richie/apps/courses/templates/courses/cms/fragment_person_glimpse.html
  src/richie/apps/courses/templates/courses/cms/person_detail.html
  src/richie/apps/courses/templates/courses/plugins/person.html
  src/richie/apps/demo/management/commands/create_demo_site.py
  tests/apps/courses/test_admin_person.py
  tests/apps/courses/test_admin_person_title.py
  tests/apps/courses/test_cms_plugins_person.py
  tests/apps/courses/test_cms_wizards_person.py
  tests/apps/courses/test_models_person.py
  tests/apps/courses/test_models_person_title.py
  tests/apps/courses/test_templates_organization_detail.py
  tests/apps/courses/test_templates_person_detail.py
Labels: improvement

#735 🔖(chore) bump release to 1.3.0
  CHANGELOG.md
  setup.cfg
  src/frontend/package.json
Labels: FUN

#739 💄(organizations) rework organization images
  CHANGELOG.md
  src/frontend/scss/objects/_organization_glimpses.scss
  src/frontend/scss/templates/courses/cms/_course_detail.scss
  src/frontend/scss/templates/courses/cms/_organization_detail.scss
  src/richie/apps/courses/templates/courses/cms/fragment_organization_glimpse.html
  src/richie/apps/courses/templates/courses/cms/fragment_organization_main_logo.html
  src/richie/apps/courses/templates/courses/cms/organization_detail.html
  tests/apps/courses/test_cms_plugins_organization.py
  tests/apps/courses/test_templates_course_detail.py
Labels: improvement

#741 🔖(chore) bump release to 1.4.0
  CHANGELOG.md
  setup.cfg
  src/frontend/package.json
Labels: feature, improvement

#737 Improve label for child filter toggle
  CHANGELOG.md
  src/frontend/js/components/SearchFilterValueParent/SearchFilterValueParent.spec.tsx
  src/frontend/js/components/SearchFilterValueParent/SearchFilterValueParent.tsx
Labels: improvement
