Repository openfun/richie, pull requests merged in 2019-05, with the labels that each got.

#684 🐛(search) fix course indexer when no related organization
  CHANGELOG.md
  src/richie/apps/search/indexers/courses.py
  tests/apps/search/test_indexers_courses.py
Labels: bug

#686 ✨(statics) allow to dynamically set webpack publicPath
  CHANGELOG.md
  src/frontend/.prettierignore
  src/frontend/public-path.js
  src/frontend/webpack.config.js
  src/richie/apps/core/context_processors.py
  src/richie/apps/search/templates/search/search.html
Labels: improvement

#688 🔧(project) improve Makefile readability
  CHANGELOG.md
  Makefile
Labels: improvement, needs review

#691 🐛(courses) return error for invalid slugs on page creation
  CHANGELOG.md
  src/richie/apps/courses/cms_wizards.py
  tests/apps/courses/test_cms_wizards_blogpost.py
  tests/apps/courses/test_cms_wizards_category.py
  tests/apps/courses/test_cms_wizards_course.py
  tests/apps/courses/test_cms_wizards_course_run.py
  tests/apps/courses/test_cms_wizards_organization.py
  tests/apps/courses/test_cms_wizards_person.py
Labels: bug

#696 🐛(demo) fix and test the create_demo_site management command
  src/richie/apps/core/helpers.py
  src/richie/apps/demo/defaults.py
  src/richie/apps/demo/management/commands/create_demo_site.py
  tests/apps/demo/test_commands_create_demo_site.py
Labels: bug

#701 ♻️(core) remove dependency to `factory` in production
  CHANGELOG.md
  src/richie/apps/core/factories.py
  src/richie/apps/core/helpers.py
  src/richie/apps/courses/factories.py
  src/richie/apps/demo/management/commands/create_demo_site.py
  tests/apps/core/test_helpers.py
  tests/apps/courses/test_cms_plugins_blogpost.py
  tests/apps/courses/test_models_category.py
  tests/apps/courses/test_models_organization.py
  tests/apps/courses/test_models_person.py
  tests/apps/demo/test_helpers.py
  tests/apps/search/test_templates_search.py
Labels: dependencies

#706 ⬆️((demo) add factory boy as dependency to the sandbox for demo
  setup.cfg
Labels: dependencies

#707 ⚡️(helpers) make recursive_page_creation idempotent
  CHANGELOG.md
  src/richie/apps/core/helpers.py
  tests/apps/core/test_helpers.py
Labels: improvement, needs review

#711 🐛(courses) fix the blockplugin template tag in edit mode
  CHANGELOG.md
  src/richie/apps/courses/templatetags/extra_tags.py
  tests/apps/courses/test_templatetags_extra_tags_block_plugin.py
Labels: bug, critical

#712 🚸(init) respect existing home page and multiple sites on init command
  CHANGELOG.md
  src/richie/apps/core/helpers.py
  tests/apps/core/test_helpers.py
Labels: improvement

#713 🔖(chore) bump release to 1.0.0
  CHANGELOG.md
  setup.cfg
  src/frontend/package.json
Labels: FUN

#714 ⚡️(circleci) speed up CI by removing depending on linting for tests
  .circleci/config.yml
Labels: improvement
