Repository openfun/richie, pull requests merged in 2019-04, with the labels that each got.

#575 🚸(courses) simplify page title frontend editing
  src/richie/apps/courses/templates/courses/cms/category_detail.html
  src/richie/apps/courses/templates/courses/cms/course_detail.html
  src/richie/apps/courses/templates/courses/cms/course_run_detail.html
  src/richie/apps/courses/templates/courses/cms/organization_detail.html
Labels: easy pick, improvement

#566 I18n support
  .circleci/config.yml
  .gitignore
  MANIFEST.in
  Makefile
  crowdin/config.yml
  docker-compose.yml
  docker/compose/ci/postgresql/docker-compose.yml
  env.d/development/crowdin.dist
  scripts/i18n/upload.js
  scripts/package.json
  src/frontend/.prettierignore
  src/frontend/js/index.tsx
  src/frontend/js/translations/fr_CA.json
  src/frontend/js/translations/fr_CA.po
  src/frontend/js/translations/fr_FR.json
  src/frontend/js/translations/fr_FR.po
  src/frontend/package.json
  src/frontend/tsconfig.json
  src/richie/apps/core/templates/richie/base.html
  src/richie/apps/search/defaults.py
  src/richie/apps/search/templates/search/search.html
  src/richie/apps/search/templatetags/__init__.py
  src/richie/apps/search/templatetags/search_tags.py
  src/richie/locale/fr_CA/LC_MESSAGES/django.mo
  src/richie/locale/fr_CA/LC_MESSAGES/django.po
  src/richie/locale/fr_FR/LC_MESSAGES/django.mo
  src/richie/locale/fr_FR/LC_MESSAGES/django.po
  tests/apps/search/test_templates_search.py
  tests/apps/search/test_templatetags_search_tags.py
Labels: FUN, feature

#579 🐛(organizations) add empty image fillers on organization detail
  src/frontend/scss/templates/courses/cms/_organization_detail.scss
  src/richie/apps/courses/templates/courses/cms/organization_detail.html
Labels: bug

#584 🎨(project) rename plugin group to richie
  sandbox/settings.py
  src/richie/apps/courses/cms_plugins.py
  src/richie/plugins/large_banner/cms_plugins.py
  src/richie/plugins/plain_text/cms_plugins.py
  src/richie/plugins/section/cms_plugins.py
  src/richie/plugins/simple_text_ckeditor/cms_plugins.py
Labels: easy pick, improvement

#586 🔧(blog) allow adding blog post plugins on the home page
  sandbox/settings.py
Labels: easy pick, improvement

#581 Standardize the Makefile
  Makefile
Labels: FUN, improvement, needs review

#561 Allow searching partial words
  src/richie/apps/search/index_manager.py
  src/richie/apps/search/indexers/categories.py
  src/richie/apps/search/indexers/courses.py
  src/richie/apps/search/indexers/organizations.py
  src/richie/apps/search/partial_mappings.py
  src/richie/apps/search/text_indexing.py
  tests/apps/search/test_autocomplete_categories.py
  tests/apps/search/test_autocomplete_courses.py
  tests/apps/search/test_autocomplete_organizations.py
  tests/apps/search/test_partial_mappings.py
  tests/apps/search/test_query_courses.py
  tests/apps/search/test_query_courses_edge_cases.py
Labels: improvement, needs review

#593 🐛(project) fix typo about 'lint-back-flake8' in Makefile
  Makefile
Labels: bug

#591 refactor paths for frontend tasks in circleci
  .circleci/config.yml
Labels: bug

#588 ✨(demo) update create_demo_site for last added changes
  sandbox/settings.py
  src/richie/apps/core/helpers.py
  src/richie/apps/core/management/commands/create_demo_site.py
  src/richie/apps/core/templates/richie/single_column.html
  src/richie/apps/courses/helpers.py
  tests/apps/core/test_helpers.py
  tests/apps/core/test_language_chooser.py
  tests/apps/core/test_pages.py
  tests/apps/courses/test_admin_organization.py
  tests/apps/courses/test_cms_plugins_blogpost.py
  tests/apps/courses/test_cms_plugins_category.py
  tests/apps/courses/test_cms_plugins_course.py
  tests/apps/courses/test_cms_plugins_organization.py
  tests/apps/courses/test_cms_plugins_person.py
  tests/apps/courses/test_cms_toolbars.py
  tests/apps/courses/test_cms_wizards_blogpost.py
  tests/apps/courses/test_cms_wizards_category.py
  tests/apps/courses/test_cms_wizards_course.py
  tests/apps/courses/test_cms_wizards_course_run.py
  tests/apps/courses/test_cms_wizards_organization.py
  tests/apps/courses/test_cms_wizards_person.py
  tests/apps/courses/test_models_category.py
  tests/apps/courses/test_models_course.py
  tests/apps/courses/test_templatetags_extra_tags_page_placeholder.py
Labels: improvement

#595 🐛(manifest) add missing extensions in MANIFEST.in file
  MANIFEST.in
Labels: bug

#596 🐛(i18n) display human languages on link title of language picker
  src/richie/apps/core/templates/menu/language_menu.html
Labels: bug

#594 💄(layout) improve styling images and CKEditor usage
  sandbox/settings.py
  src/frontend/scss/_main.scss
  src/frontend/scss/elements/_images.scss
  src/frontend/scss/templates/richie/section/_section.scss
  src/richie/static/richie/css/ckeditor.css
Labels: improvement

#602 📦(dependencies) refactor app/sandbox dependencies
  Dockerfile
  docker/images/alpine/Dockerfile
  docker/images/alpine/ci/Dockerfile
  docker/images/alpine/dev/Dockerfile
  setup.cfg
Labels: dependencies, improvement, needs review

#600 🌐(i18n) download and compile latest translations
  src/frontend/js/translations/fr_CA.json
  src/frontend/js/translations/fr_CA.po
  src/frontend/js/translations/fr_FR.json
  src/frontend/js/translations/fr_FR.po
  src/richie/locale/fr_CA/LC_MESSAGES/django.mo
  src/richie/locale/fr_CA/LC_MESSAGES/django.po
  src/richie/locale/fr_FR/LC_MESSAGES/django.mo
  src/richie/locale/fr_FR/LC_MESSAGES/django.po
Labels: FUN

#605 🐳(front) build frontend in production mode
  Dockerfile
  src/frontend/package.json
Labels: improvement

#606 🌐(search) replace gettext by ugettext_lazy in the defaults file
  src/richie/apps/search/defaults.py
  tests/apps/search/test_query_courses_edge_cases.py
Labels: improvement

#612 🔖(chore) bump release to 1.0.0-beta.4
  CHANGELOG.md
  setup.cfg
  src/frontend/package.json
Labels: improvement

#608 👷(circleci) add check CHANGELOG job
  .circleci/config.yml
Labels: FUN, improvement, needs review

#615 🐳(frontend) improve build
  CHANGELOG.md
  Dockerfile
Labels: improvement, needs review

#609 💄(layout) improve how empty pages look
  src/frontend/scss/_main.scss
  src/frontend/scss/mixins/_empty.scss
  src/frontend/scss/templates/courses/cms/_blogpost_detail.scss
  src/frontend/scss/templates/courses/cms/_category_detail.scss
  src/frontend/scss/templates/courses/cms/_course_detail.scss
  src/frontend/scss/templates/courses/cms/_organization_detail.scss
  src/frontend/scss/templates/courses/cms/_organization_list.scss
  src/frontend/scss/templates/courses/cms/_person_detail.scss
  src/frontend/scss/templates/courses/plugins/_category_plugin.scss
  src/frontend/scss/templates/courses/plugins/_organization_plugin.scss
  src/frontend/scss/templates/richie/section/_section.scss
  src/richie/apps/courses/templates/courses/cms/blogpost_detail.html
  src/richie/apps/courses/templates/courses/cms/category_detail.html
  src/richie/apps/courses/templates/courses/cms/course_detail.html
  src/richie/apps/courses/templates/courses/cms/fragment_course_content.html
  src/richie/apps/courses/templates/courses/cms/fragment_organization_main_logo.html
  src/richie/apps/courses/templates/courses/cms/organization_detail.html
  src/richie/apps/courses/templates/courses/cms/organization_list.html
  src/richie/apps/courses/templates/courses/cms/person_detail.html
  src/richie/apps/courses/templates/courses/plugins/organization.html
Labels: improvement

#563 ✨(search) implement parent & children filters in the frontend
  CHANGELOG.md
  src/frontend/js/components/SearchFilterGroup/SearchFilterGroup.spec.tsx
  src/frontend/js/components/SearchFilterGroup/SearchFilterGroup.tsx
  src/frontend/js/components/SearchFilterValueParent/SearchFilterValueParent.spec.tsx
  src/frontend/js/components/SearchFilterValueParent/SearchFilterValueParent.tsx
  src/frontend/js/types/filters.ts
Labels: improvement

#634 🔧(pyup) ignore direct dependencies pinning
  setup.cfg
Labels: dependencies, improvement, needs review

#639 🔖(chore) bump release to 1.0.0-beta.5
  CHANGELOG.md
  setup.cfg
  src/frontend/package.json
Labels: FUN, needs review

#637 💄(person) style persons list and fix minor layout feedbacks
  sandbox/settings.py
  src/frontend/scss/_colors.scss
  src/frontend/scss/_main.scss
  src/frontend/scss/components/_content.scss
  src/frontend/scss/objects/_course_glimpses.scss
  src/frontend/scss/objects/_person_glimpses.scss
  src/frontend/scss/templates/courses/cms/_course_detail.scss
  src/frontend/scss/templates/courses/cms/_person_detail.scss
  src/frontend/scss/templates/courses/plugins/_person_plugin.scss
  src/frontend/scss/templates/richie/section/_section.scss
  src/richie/apps/core/management/commands/create_demo_site.py
  src/richie/apps/courses/templates/courses/cms/course_detail.html
  src/richie/apps/courses/templates/courses/cms/fragment_course_glimpse.html
  src/richie/apps/courses/templates/courses/cms/fragment_person_glimpse.html
  src/richie/apps/courses/templates/courses/cms/person_list.html
  src/richie/apps/courses/templates/courses/plugins/person.html
  tests/apps/courses/test_cms_plugins_person.py
Labels: improvement

#642 🐛(circleci) fix PyPI package upload job
  .circleci/config.yml
Labels: bug, critical, needs review

#636 💄(category) add sub categories in detail and better categories list
  CHANGELOG.md
  sandbox/settings.py
  src/frontend/scss/_main.scss
  src/frontend/scss/objects/_blogpost_glimpses.scss
  src/frontend/scss/objects/_category_glimpses.scss
  src/frontend/scss/templates/courses/cms/_blogpost_detail.scss
  src/frontend/scss/templates/courses/plugins/_category_plugin.scss
  src/frontend/scss/templates/courses/plugins/_organization_plugin.scss
  src/richie/apps/courses/models/category.py
  src/richie/apps/courses/templates/courses/cms/blogpost_detail.html
  src/richie/apps/courses/templates/courses/cms/category_detail.html
  src/richie/apps/courses/templates/courses/cms/category_list.html
  src/richie/apps/courses/templates/courses/cms/fragment_blogpost_glimpse.html
  src/richie/apps/courses/templates/courses/cms/fragment_category_glimpse.html
  src/richie/apps/courses/templates/courses/plugins/category_plugin.html
  src/richie/apps/demo/defaults.py
  tests/apps/courses/test_cms_plugins_category.py
  tests/apps/courses/test_models_category.py
Labels: improvement

#653 🚸(demo) add categories to persons on the demo site
  src/richie/apps/demo/defaults.py
  src/richie/apps/demo/management/commands/create_demo_site.py
Labels: easy pick, improvement

#652 💄(organization) add organization glimpse template
  CHANGELOG.md
  src/frontend/scss/_main.scss
  src/frontend/scss/objects/_organization_glimpses.scss
  src/frontend/scss/templates/courses/cms/_organization_list.scss
  src/richie/apps/courses/templates/courses/cms/fragment_organization_glimpse.html
  src/richie/apps/courses/templates/courses/cms/organization_list.html
  src/richie/apps/courses/templates/courses/plugins/organization.html
  tests/apps/courses/test_cms_plugins_organization.py
  tests/apps/courses/test_templates_course_detail.py
  tests/apps/courses/test_templates_course_run_detail.py
Labels: improvement

#657 🔖(chore) bump release to 1.0.0-beta.6
  CHANGELOG.md
  setup.cfg
  src/frontend/package.json
Labels: FUN, needs review

#658 🌐(i18n) compile latest translations
  src/frontend/js/translations/fr_CA.po
  src/frontend/js/translations/fr_FR.po
  src/richie/locale/fr_CA/LC_MESSAGES/django.mo
  src/richie/locale/fr_CA/LC_MESSAGES/django.po
  src/richie/locale/fr_FR/LC_MESSAGES/django.mo
  src/richie/locale/fr_FR/LC_MESSAGES/django.po
Labels: FUN

#659 Fix ci hub job
  .circleci/config.yml
Labels: bug, improvement

#660 🐛(search) fix a display glitch in active parent filters
  CHANGELOG.md
  src/frontend/js/components/SearchFilterValueParent/SearchFilterValueParent.spec.tsx
  src/frontend/js/components/SearchFilterValueParent/SearchFilterValueParent.tsx
  src/frontend/scss/objects/_search-filter-value.scss
Labels: bug

#661 🔖(chore) bump release to 1.0.0-beta.7
  CHANGELOG.md
  setup.cfg
  src/frontend/package.json
Labels: improvement

#656 Refactor SearchSuggestField to use more functional tests
  CHANGELOG.md
  src/frontend/js/components/SearchSuggestField/SearchSuggestField.spec.tsx
  src/frontend/js/components/SearchSuggestField/SearchSuggestField.tsx
  src/frontend/js/utils/searchSuggest/getSuggestionsSection.ts
  src/frontend/js/utils/searchSuggest/suggestionHumanName.spec.ts
  src/frontend/js/utils/searchSuggest/suggestionHumanName.ts
Labels: improvement

#665 ✨(organizations) show related persons on the organization detail page
  CHANGELOG.md
  src/richie/apps/courses/models/organization.py
  src/richie/apps/courses/models/person.py
  src/richie/apps/courses/templates/courses/cms/organization_detail.html
  tests/apps/courses/test_models_organization.py
  tests/apps/courses/test_templates_blogpost_detail.py
  tests/apps/courses/test_templates_category_detail.py
  tests/apps/courses/test_templates_organization_detail.py
  tests/apps/courses/test_templates_person_detail.py
Labels: feature

#667 🚸(demo) associate persons to organizations on the demo site
  CHANGELOG.md
  src/richie/apps/demo/defaults.py
  src/richie/apps/demo/management/commands/create_demo_site.py
Labels: improvement

#674 Show results count in course search
  CHANGELOG.md
  src/frontend/js/components/CourseGlimpseList/CourseGlimpseList.spec.tsx
  src/frontend/js/components/CourseGlimpseList/CourseGlimpseList.tsx
  src/frontend/js/components/Search/Search.tsx
  src/frontend/scss/objects/_course_glimpses.scss
Labels: feature request

#675 🌐(i18n) compile latest translations
  src/frontend/js/translations/fr_CA.json
  src/frontend/js/translations/fr_CA.po
  src/frontend/js/translations/fr_FR.json
  src/frontend/js/translations/fr_FR.po
  src/richie/locale/fr_CA/LC_MESSAGES/django.mo
  src/richie/locale/fr_CA/LC_MESSAGES/django.po
  src/richie/locale/fr_FR/LC_MESSAGES/django.mo
  src/richie/locale/fr_FR/LC_MESSAGES/django.po
Labels: FUN

#682 Improve suggestion typings and simplify code
  src/frontend/js/components/SearchSuggestField/SearchSuggestField.tsx
  src/frontend/js/components/SearchSuggestField/getSuggestionsSection.ts
  src/frontend/js/components/SearchSuggestField/getSuggestionsSections.spec.ts
  src/frontend/js/types/Suggestion.ts
  src/frontend/js/types/searchSuggest.ts
  src/frontend/js/utils/searchSuggest/suggestionsFromSection.spec.ts
  src/frontend/js/utils/searchSuggest/suggestionsFromSection.ts
Labels: improvement
