Repository openfun/richie, pull requests merged in 2020-12, with the labels that each got.

#1208 📌(djangocms-admin-style) use a forked version waiting next release
  Dockerfile
Labels: dependencies

#1209 🔖(chore) bump version to 2.0.0-beta.22
  CHANGELOG.md
  setup.cfg
  src/frontend/package.json
  tests_e2e/package.json
  website/package.json
Labels: improvement

#1213 🔒(courses) add permissions to course run admin
  CHANGELOG.md
  src/richie/apps/courses/admin.py
  src/richie/apps/courses/helpers.py
  tests/apps/courses/test_admin_course_run.py
  tests/apps/courses/test_admin_form_course_run.py
Labels: improvement

#1215 🐛(demo) fix generate demo site when default language is set to "fr"
  CHANGELOG.md
  src/richie/apps/courses/factories.py
  src/richie/apps/demo/management/commands/create_demo_site.py
Labels: bug

#1223 🐛(frontend) fix intlrelativeformat polyfill
  CHANGELOG.md
  src/frontend/js/index.tsx
Labels: bug

#1225 🐛(settings) sentry dsn is misconfigured
  CHANGELOG.md
  sandbox/settings.py
Labels: bug

#1224 ♻️(CourseRunEnrollment) pass course run data from data-props
  CHANGELOG.md
  src/frontend/js/components/CourseRunEnrollment/index.spec.tsx
  src/frontend/js/components/CourseRunEnrollment/index.tsx
  src/richie/apps/courses/templates/courses/cms/fragment_course_run.html
  src/richie/apps/courses/templatetags/extra_tags.py
  tests/apps/courses/test_templates_course_detail.py
  tests/apps/courses/test_templatetags_extra_tags_course_enrollment_widget_props.py
Labels: improvement
