Repository openfun/richie, pull requests merged in 2020-07, with the labels that each got.

#1070 🐛 Fix the broken course search field after filters are reset
  CHANGELOG.md
  src/frontend/js/components/SearchSuggestField/index.spec.tsx
  src/frontend/js/components/SearchSuggestField/index.tsx
Labels: bug, needs review

#1073 🔖(chore) bump version to 2.0.0-beta.9
  CHANGELOG.md
  setup.cfg
  src/frontend/package.json
  tests_e2e/package.json
  website/package.json
Labels: FUN Team

#1077 ✨(layout) add Linkedin icon and new section template "septenary"
  CHANGELOG.md
  sandbox/settings.py
  src/frontend/scss/settings/_colors.scss
  src/frontend/scss/tools/_detail.scss
  src/richie/apps/core/static/richie/images/components/waves.svg
  src/richie/apps/core/templates/richie/icons.html
  src/richie/apps/core/templates/social-networks/blogpost-badges.html
  src/richie/apps/core/templates/social-networks/course-badges.html
  src/richie/apps/core/templates/social-networks/footer-badges.html
  src/richie/plugins/section/defaults.py
  src/richie/plugins/section/templates/richie/section/section_septenary.html
Labels: improvement

#1079 🔨 Enable live-debugging in app container
  docker-compose.yml
Labels: improvement

#1085 ✨(core) add a plugin for django-redis that supports Redis Sentinel
  .circleci/config.yml
  CHANGELOG.md
  docker-compose.yml
  sandbox/settings.py
  setup.cfg
  src/richie/apps/core/cache.py
  tests/apps/core/test_cache.py
Labels: feature
