Repository openfun/richie, pull requests merged in 2020-08, with the labels that each got.

#1094 ✨(sandbox) allow to configure cache settings with environment variables
  CHANGELOG.md
  sandbox/settings.py
Labels: feature

#1093 🐛(docker) fix inconsistent sentinel state when running tests
  bin/pytest
  docker-compose.yml
Labels: bug

#1098 🐛(dependencies) fix typo in python dev dependencies
  CHANGELOG.md
  setup.cfg
  src/frontend/package.json
  tests_e2e/package.json
  website/package.json
Labels: bug

#1059 💄(layout) add default image for empty category, organization and person
  CHANGELOG.md
  src/frontend/scss/tools/_detail.scss
  src/richie/apps/core/static/richie/images/empty/organization_banner.jpg
  src/richie/apps/core/static/richie/images/empty/organization_logo.png
  src/richie/apps/core/static/richie/images/empty/person_portrait.png
  src/richie/apps/courses/templates/courses/cms/fragment_organization_glimpse.html
  src/richie/apps/courses/templates/courses/cms/fragment_person_glimpse.html
  src/richie/apps/courses/templates/courses/cms/organization_detail.html
  src/richie/apps/courses/templates/courses/cms/person_detail.html
Labels: improvement

#1106 🔖(chore) bump version to 2.0.0-beta.12
  CHANGELOG.md
  setup.cfg
  src/frontend/package.json
  tests_e2e/package.json
  website/package.json
Labels: improvement

#1108 🔖(chore) bump version to 2.0.0-beta.13
  CHANGELOG.md
  setup.cfg
  src/frontend/js/translations/es-ES.json
  src/frontend/js/translations/es-ES.po
  src/frontend/js/translations/fr-CA.json
  src/frontend/js/translations/fr-CA.po
  src/frontend/js/translations/fr-FR.json
  src/frontend/js/translations/fr-FR.po
  src/frontend/package.json
  src/richie/locale/es_ES/LC_MESSAGES/django.mo
  src/richie/locale/es_ES/LC_MESSAGES/django.po
  src/richie/locale/fr_CA/LC_MESSAGES/django.mo
  src/richie/locale/fr_CA/LC_MESSAGES/django.po
  src/richie/locale/fr_FR/LC_MESSAGES/django.mo
  src/richie/locale/fr_FR/LC_MESSAGES/django.po
  tests_e2e/package.json
  website/package.json
Labels: feature
