Repository openfun/richie, pull requests merged in 2020-10, with the labels that each got.

#1159 🚸(plugins) improve sanitizing of input text on CKEditor plugin
  CHANGELOG.md
  src/richie/plugins/simple_text_ckeditor/forms.py
  src/richie/plugins/simple_text_ckeditor/validators.py
  tests/plugins/simple_text_ckeditor/test_forms.py
  tests/plugins/simple_text_ckeditor/test_validators.py
Labels: bug

#1164 🐛(organizations) fix organizations list page hiding unpublished
  CHANGELOG.md
  src/richie/apps/courses/templates/courses/cms/blogpost_list.html
  src/richie/apps/courses/templates/courses/cms/organization_list.html
  tests/apps/courses/test_templates_organization_list.py
Labels: bug

#1166 🔖(chore) bump version to 2.0.0-beta.16
  CHANGELOG.md
  setup.cfg
  src/frontend/package.json
  tests_e2e/package.json
  website/package.json
Labels: FUN Team

#1169 🐛 (webpack 5) update config file
  .circleci/config.yml
  src/frontend/webpack.config.js
Labels: critical, needs review
