Repository openfun/richie, pull requests merged in 2020-03, with the labels that each got.

#964 💄(layout) unique breadcrumb layout for course run page
  CHANGELOG.md
  src/richie/apps/courses/templates/courses/cms/course_run_detail.html
  src/richie/apps/courses/templates/courses/cms/fragment_course_run_breadcrumb.html
  tests/apps/courses/test_templates_course_run_detail.py
Labels: bug

#968 🐛(permissions) prevent creating duplicate permissions programmatically
  CHANGELOG.md
  src/richie/apps/courses/models/course.py
  tests/apps/courses/test_models_course.py
  tests/apps/courses/test_models_organization.py
Labels: bug

#967 🚸(toolbar) improve plugin description displayed in side toolbar
  CHANGELOG.md
  src/richie/apps/core/models.py
  src/richie/apps/courses/cms_plugins.py
  src/richie/apps/courses/models/blog.py
  src/richie/apps/courses/models/category.py
  src/richie/apps/courses/models/course.py
  src/richie/apps/courses/models/organization.py
  src/richie/apps/courses/models/person.py
  src/richie/apps/courses/models/program.py
Labels: improvement

#969 ♻️(core) remove context processor that was added since latest release
  UPGRADE.md
  sandbox/settings.py
  src/richie/apps/core/context_processors.py
Labels: FUN Team, improvement

#974 🐛Fix an issue with full-text search in course search
  CHANGELOG.md
  src/frontend/js/components/SearchSuggestField/index.spec.tsx
  src/frontend/js/components/SearchSuggestField/index.tsx
Labels: bug, needs review

#976 ✨(blogposts) Add a variant option for blogpost glimpses
  CHANGELOG.md
  src/richie/apps/courses/cms_plugins.py
  src/richie/apps/courses/defaults.py
  src/richie/apps/courses/migrations/0014_auto_20200309_2343.py
  src/richie/apps/courses/models/blog.py
  src/richie/apps/courses/templates/courses/cms/fragment_blogpost_glimpse.html
  src/richie/apps/courses/templates/courses/plugins/blogpost.html
  tests/apps/courses/test_cms_plugins_blogpost.py
Labels: feature
