Repository openfun/richie, pull requests merged in 2020-04, with the labels that each got.

#979 🐛 Empty the search input field when the filters are cleared
  CHANGELOG.md
  src/frontend/js/components/SearchFiltersPane/_styles.scss
  src/frontend/js/components/SearchSuggestField/index.spec.tsx
  src/frontend/js/components/SearchSuggestField/index.tsx
Labels: bug, needs review

#986 Release 1.17.0
  CHANGELOG.md
  setup.cfg
  src/frontend/package.json
  tests_e2e/package.json
  website/package.json
  website/versions.json
Labels: bug, improvement

#987 📝(upgrade) add missing release markers to UPGRADE.md
  UPGRADE.md
Labels: bug

#988 🔖(chore) bump version to 2.0.0-beta.0
  .circleci/config.yml
  CHANGELOG.md
  UPGRADE.md
  setup.cfg
  src/frontend/package.json
  tests_e2e/package.json
  website/package.json
Labels: improvement

#990 👌(course) enforce course glimpse to be on single line
  CHANGELOG.md
  src/frontend/scss/objects/_course_glimpses.scss
Labels: improvement

#991 🐛(section) remove useless dependency to nesteditem migration
  CHANGELOG.md
  src/richie/plugins/section/migrations/0005_migrate_sectionlist_to_nesteditem.py
Labels: bug, critical

#992 ✨(courses) limit number of related objects on all detail pages
  CHANGELOG.md
  src/frontend/scss/components/templates/richie/section/_section.scss
  src/richie/apps/core/context_processors.py
  src/richie/apps/core/defaults.py
  src/richie/apps/core/templates/richie/pagination.html
  src/richie/apps/courses/models/category.py
  src/richie/apps/courses/models/organization.py
  src/richie/apps/courses/templates/courses/cms/category_detail.html
  src/richie/apps/courses/templates/courses/cms/organization_detail.html
  src/richie/apps/courses/templates/courses/cms/person_detail.html
  src/richie/apps/courses/templates/courses/plugins/organizations_by_category.html
  src/richie/apps/demo/defaults.py
  src/richie/apps/search/indexers/categories.py
  src/richie/apps/search/indexers/courses.py
  src/richie/apps/search/indexers/organizations.py
  tests/apps/courses/test_templates_category_detail.py
  tests/apps/courses/test_templates_organization_detail.py
  tests/apps/courses/test_templates_person_detail.py
Labels: improvement

#993 🗃(courses|plugins) liquidate pending migrations in view of v2.0.0
  CHANGELOG.md
  src/richie/apps/courses/migrations/0016_auto_20200417_1237.py
  src/richie/plugins/nesteditem/migrations/0002_auto_20200417_1237.py
Labels: FUN Team

#995 🎨(blogposts) add blocks to each part of the blogpost detail template
  CHANGELOG.md
  src/richie/apps/courses/templates/courses/cms/blogpost_detail.html
  src/richie/apps/courses/templates/courses/cms/course_detail.html
Labels: improvement
