Repository openfun/richie, pull requests merged in 2020-09, with the labels that each got.

#1112 ✏️ (docs) fix misspelling
  docs/docker-development.md
  docs/native-installation.md
  website/versioned_docs/version-1.12/docker-development.md
Labels: docs website

#1114 🔧(cms) limit number of plugin in course description to one
  CHANGELOG.md
  src/richie/apps/courses/settings/__init__.py
Labels: improvement

#1115 ✨(back) allow to configure EDX_USER_PROFILE_TO_DJANGO setting
  CHANGELOG.md
  sandbox/settings.py
  src/richie/apps/core/backends.py
Labels: improvement

#1117 🚸(Search) scroll after course fetching
  CHANGELOG.md
  src/frontend/js/components/Search/index.spec.tsx
  src/frontend/js/components/Search/index.tsx
  src/frontend/js/data/useCourseSearchParams/index.spec.tsx
  src/frontend/js/data/useCourseSearchParams/index.ts
Labels: improvement

#1122 🐛(back) fix how EDX_USER_PROFILE_TO_DJANGO default value is set
  CHANGELOG.md
  src/richie/apps/core/backends.py
Labels: bug

#1128 ♻️(plugins) allow empty content on glimpse plugins
  CHANGELOG.md
  src/richie/apps/demo/management/commands/create_demo_site.py
  src/richie/plugins/glimpse/migrations/0002_auto_20200915_1312.py
  src/richie/plugins/glimpse/models.py
  tests/plugins/glimpse/test_cms_plugins.py
Labels: improvement

#1129 👽(project) point powered by to https://richie.education
  src/richie/apps/core/templates/richie/base.html
Labels: improvement

#1134 💄(frontend) fix selector arrow color in footer
  src/frontend/scss/components/_footer.scss
  src/frontend/scss/objects/_selector.scss
Labels: bug

#1133 📝(readme) update demo login instructions after adding OpenEdX SSO
  README.md
Labels: bug

#1137 📝(docs) add instructions to make elasticsearch system tweak permanent
  docs/docker-development.md
Labels: improvement

#1139 🐛 (frontend) handle error invalid configuration
  CHANGELOG.md
  src/frontend/jest.config.js
  src/frontend/js/utils/errors/handle.spec.ts
  src/frontend/js/utils/errors/handle.ts
  tests/apps/core/test_pages.py
Labels: bug, needs review

#1147 🔥(core) remove copyright notice from footer in base template
  CHANGELOG.md
  src/frontend/scss/components/_footer.scss
  src/richie/apps/core/templates/richie/base.html
Labels: improvement
