Repository openfun/richie, pull requests merged in 2020-05, with the labels that each got.

#1005 ✨ Improve query analyzer language selection
  CHANGELOG.md
  src/richie/apps/search/defaults.py
  src/richie/apps/search/forms.py
  tests/apps/search/test_forms_search_courses.py
  tests/apps/search/test_forms_search_items.py
  tests/apps/search/test_viewsets_categories.py
  tests/apps/search/test_viewsets_organizations.py
  tests/apps/search/test_viewsets_persons.py
Labels: bug, feature, needs review

#1009 Program glimpses and minor integration changes
  CHANGELOG.md
  sandbox/settings.py
  src/frontend/js/components/UserLogin/_styles.scss
  src/frontend/scss/components/_content.scss
  src/frontend/scss/components/_header.scss
  src/frontend/scss/components/_styleguide.scss
  src/frontend/scss/components/templates/courses/cms/_blogpost_detail.scss
  src/frontend/scss/components/templates/courses/cms/_blogpost_list.scss
  src/frontend/scss/components/templates/courses/cms/_category_detail.scss
  src/frontend/scss/components/templates/courses/cms/_category_list.scss
  src/frontend/scss/components/templates/courses/cms/_course_detail.scss
  src/frontend/scss/components/templates/courses/cms/_homepage.scss
  src/frontend/scss/components/templates/courses/cms/_organization_detail.scss
  src/frontend/scss/components/templates/courses/cms/_organization_list.scss
  src/frontend/scss/components/templates/courses/cms/_person_detail.scss
  src/frontend/scss/components/templates/courses/cms/_person_list.scss
  src/frontend/scss/components/templates/courses/cms/_program_detail.scss
  src/frontend/scss/components/templates/courses/cms/_program_list.scss
  src/frontend/scss/components/templates/richie/_single-column.scss
  src/frontend/scss/components/templates/richie/glimpse/_glimpse.scss
  src/frontend/scss/components/templates/richie/large_banner/_large_banner.scss
  src/frontend/scss/components/templates/richie/nesteditem/_nesteditem.scss
  src/frontend/scss/components/templates/search/_search.scss
  src/frontend/scss/objects/_blogpost_glimpses.scss
  src/frontend/scss/objects/_buttons.scss
  src/frontend/scss/objects/_category_glimpses.scss
  src/frontend/scss/objects/_organization_glimpses.scss
  src/frontend/scss/objects/_pagination.scss
  src/frontend/scss/objects/_program_glimpses.scss
  src/frontend/scss/objects/_react-autosuggest.scss
  src/frontend/scss/objects/_search-filter-value.scss
  src/frontend/scss/settings/_colors.scss
  src/frontend/scss/settings/_fonts.scss
  src/frontend/scss/settings/_variables.scss
  src/frontend/scss/tools/_accordion.scss
  src/richie/apps/core/static/richie/images/components/arc-white.svg
  src/richie/apps/core/static/richie/images/components/curve-white.svg
  src/richie/apps/core/static/richie/images/logo-alt.png
  src/richie/apps/core/templates/richie/base.html
  src/richie/apps/core/templates/richie/homepage.html
  src/richie/apps/courses/templates/courses/cms/person_detail.html
  src/richie/plugins/section/templates/richie/section/section_tertiary.html
Labels: feature, improvement

#1010 🔖(chore) bump version to 2.0.0-beta.5
  CHANGELOG.md
  setup.cfg
  src/frontend/package.json
  tests_e2e/package.json
  website/package.json
Labels: FUN Team

#1020 🔖(chore) bump version to 2.0.0-beta.6
  CHANGELOG.md
  setup.cfg
  src/frontend/package.json
  tests_e2e/package.json
  website/package.json
Labels: FUN Team

#1021 ✨(core) allow customizing topbar contact button
  CHANGELOG.md
  src/richie/apps/core/templates/richie/base.html
Labels: improvement

#1022 ⚡️Improve <Search> performance
  CHANGELOG.md
  src/frontend/js/components/CourseGlimpse/index.tsx
  src/frontend/js/components/Root/index.tsx
  src/frontend/js/components/SearchFilterValueLeaf/index.tsx
  src/frontend/js/components/SearchSuggestField/index.spec.tsx
  src/frontend/js/data/useCourseSearchParams/index.spec.tsx
  src/frontend/js/data/useHistory/index.spec.tsx
  src/frontend/js/data/useHistory/index.tsx
Labels: improvement

#1026 🔧(courses) allow glimpse plugin in course information
  CHANGELOG.md
  src/richie/apps/courses/settings/__init__.py
Labels: improvement
