Repository openfun/richie, pull requests merged in 2020-06, with the labels that each got.

#1030 💄(plugins) large_banner hero variant refinement
  CHANGELOG.md
  src/frontend/scss/components/templates/richie/large_banner/_large_banner.scss
  src/frontend/scss/settings/_colors.scss
  src/richie/apps/demo/defaults.py
  src/richie/plugins/large_banner/forms.py
  src/richie/plugins/large_banner/templates/richie/large_banner/hero-intro.html
Labels: improvement

#1031 💄(homepage) first course glimpses on three columns on homepage
  CHANGELOG.md
  src/frontend/scss/components/templates/courses/cms/_homepage.scss
  src/richie/apps/demo/defaults.py
Labels: improvement

#1032 👌(layout) fix glitch with "scaleX" usage on wave decoration
  CHANGELOG.md
  src/frontend/scss/components/templates/courses/cms/_category_detail.scss
  src/frontend/scss/components/templates/courses/cms/_organization_detail.scss
Labels: bug, improvement

#1037 👌(section) fix alignment for category glimpses in section tiles
  CHANGELOG.md
  src/frontend/scss/components/templates/richie/section/_section.scss
Labels: bug, improvement

#1038 🔖(chore) bump version to 2.0.0-beta.7
  CHANGELOG.md
  setup.cfg
  src/frontend/package.json
  tests_e2e/package.json
  website/package.json
Labels: improvement

#1041 👌(layout) change course detail content titles to neutral dark color
  CHANGELOG.md
  src/frontend/scss/settings/_colors.scss
Labels: improvement

#1042 👌(layout) fix course detail vertical rhythm and font size
  CHANGELOG.md
  src/frontend/scss/components/templates/courses/cms/_course_detail.scss
Labels: improvement

#1040 👌(layout) add checkmark icon to course skills bullet lists
  CHANGELOG.md
  src/frontend/scss/components/templates/courses/cms/_course_detail.scss
  src/frontend/scss/settings/_colors.scss
  src/richie/apps/core/static/richie/images/components/checkmark.svg
Labels: improvement

#1043 👌(layout) fix accordion border line
  CHANGELOG.md
  src/frontend/scss/components/templates/courses/cms/_course_detail.scss
  src/frontend/scss/components/templates/richie/nesteditem/_nesteditem.scss
  src/richie/apps/core/templates/richie/base.html
Labels: bug, improvement

#1044 👌(layout) customize CMS placeholder menu for more readability
  CHANGELOG.md
  src/frontend/scss/_main.scss
  src/frontend/scss/trumps/_cms.scss
Labels: improvement

#1045 👌(section) fix basic block element alignment in section
  CHANGELOG.md
  src/frontend/scss/components/templates/richie/section/_section.scss
Labels: bug, improvement

#1047 ♻️ change the way we use our svg icons sprite to not break with CDNs
  CHANGELOG.md
  src/frontend/js/components/Search/index.tsx
  src/frontend/js/components/SearchInput/index.spec.tsx
  src/frontend/js/components/SearchInput/index.tsx
  src/frontend/js/components/SearchSuggestField/index.spec.tsx
  src/frontend/js/types/commonDataProps.ts
  src/richie/apps/core/context_processors.py
  src/richie/apps/core/templates/richie/base.html
  src/richie/apps/core/templates/richie/icons.html
  src/richie/apps/core/templates/richie/styleguide/index.html
  src/richie/apps/core/templates/social-networks/blogpost-badges.html
  src/richie/apps/core/templates/social-networks/course-badges.html
  src/richie/apps/core/templates/social-networks/footer-badges.html
  src/richie/apps/courses/templates/courses/cms/course_detail.html
  src/richie/apps/search/templates/search/search.html
  src/richie/plugins/large_banner/templates/richie/large_banner/hero-intro.html
Labels: bug, improvement

#1051 👌(layout) make login/logout CTA more visible
  CHANGELOG.md
  src/frontend/js/components/UserLogin/_styles.scss
  src/frontend/scss/settings/_colors.scss
Labels: improvement

#1052 👌(course) make course glimpse category cartouche less "aggressive"
  CHANGELOG.md
  src/frontend/scss/objects/_course_glimpses.scss
Labels: improvement

#1054 👌(layout) improve accessibility on 'body-mentions'
  CHANGELOG.md
  src/frontend/scss/components/_footer.scss
  src/frontend/scss/settings/_colors.scss
Labels: improvement

#1053 👌(layout) add template block around footer slogan
  CHANGELOG.md
  src/richie/apps/core/templates/richie/base.html
Labels: improvement

#1055 🔖(chore) bump version to 2.0.0-beta.8
  CHANGELOG.md
  setup.cfg
  src/frontend/package.json
  tests_e2e/package.json
  website/package.json
Labels: FUN Team, improvement

#1056 💄 add icons to course glimpse footer & organization
  CHANGELOG.md
  src/frontend/js/components/CourseGlimpse/CourseGlimpseFooter.tsx
  src/frontend/js/components/CourseGlimpse/index.spec.tsx
  src/frontend/js/components/CourseGlimpse/index.tsx
  src/frontend/scss/objects/_course_glimpses.scss
  src/richie/apps/core/templates/richie/icons.html
  src/richie/apps/courses/templates/courses/cms/fragment_course_glimpse.html
  tests/apps/courses/test_cms_plugins_course.py
Labels: improvement

#1060 💄(course) improve search error message layout
  CHANGELOG.md
  src/frontend/js/components/Search/index.tsx
  src/frontend/scss/components/templates/search/_search.scss
  src/frontend/scss/settings/_colors.scss
  src/richie/apps/core/templates/richie/icons.html
Labels: improvement

#1061 👌(layout) lower page detail title and other minor issues
  CHANGELOG.md
  src/frontend/scss/components/_content.scss
  src/frontend/scss/components/_header.scss
  src/frontend/scss/components/templates/courses/cms/_category_detail.scss
  src/frontend/scss/components/templates/courses/cms/_organization_detail.scss
  src/frontend/scss/components/templates/richie/large_banner/_large_banner.scss
  src/frontend/scss/components/templates/richie/nesteditem/_nesteditem.scss
  src/frontend/scss/objects/_breadcrumbs.scss
  src/frontend/scss/settings/_variables.scss
Labels: bug, improvement

#1063 💄(nesteditem) fix nesteditem list variant to act like a basic list
  CHANGELOG.md
  src/frontend/scss/components/_footer.scss
  src/frontend/scss/components/templates/richie/nesteditem/_nesteditem.scss
Labels: bug
