Repository openfun/richie, pull requests merged in 2021-02, with the labels that each got.

#1279 🐛(frontend) fix autosuggest to redirect directly on course page
  CHANGELOG.md
  src/frontend/js/components/RootSearchSuggestField/index.spec.tsx
  src/frontend/js/components/RootSearchSuggestField/index.tsx
Labels: bug

#1284 🚑(dependency) pin django-treebeard to 4.4
  CHANGELOG.md
  setup.cfg
Labels: bug, critical

#1287 ✨(courses) add "archived open" state for course runs
  CHANGELOG.md
  src/frontend/js/components/CourseRunEnrollment/index.tsx
  src/frontend/js/types/Course.ts
  src/frontend/js/types/index.ts
  src/richie/apps/courses/models/course.py
  src/richie/apps/courses/templates/courses/cms/course_detail.html
  src/richie/apps/search/forms.py
  src/richie/apps/search/indexers/courses.py
  tests/apps/courses/test_models_course_run.py
  tests/apps/courses/test_models_course_state.py
  tests/apps/courses/test_templates_course_detail.py
  tests/apps/search/test_query_courses.py
Labels: feature
