Repository openfun/richie, pull requests merged in 2021-05, with the labels that each got.

#1354 🔖(chore) bump version to 2.6.0
  CHANGELOG.md
  setup.cfg
  src/frontend/i18n/locales/pt-PT.json
  src/frontend/js/translations/pt-PT.json
  src/frontend/package.json
  src/richie/locale/pt_PT/LC_MESSAGES/django.mo
  src/richie/locale/pt_PT/LC_MESSAGES/django.po
  tests_e2e/package.json
  website/package.json
  website/versions.json
Labels: FUN Team

#1351 🔧(docker) use a custom name for the app service on default network
  docker-compose.yml
  docker/files/etc/nginx/conf.d/default.conf
Labels: bug

#1366 🔧(renovate) fix ignored python dependencies
  renovate.json
  setup.cfg
Labels: bug

#1368 🔍️(i18n) add "hreflang" meta to avoid duplicates in search engines
  CHANGELOG.md
  src/richie/apps/core/templates/richie/base.html
  src/richie/apps/core/templates/richie/hreflang.html
  tests/apps/core/test_pages.py
Labels: improvement
