Repository openfun/richie, pull requests merged in 2021-03, with the labels that each got.

#1296 ✨(blogposts) order blog posts by reverse publication date on list view
  CHANGELOG.md
  src/richie/apps/courses/templates/courses/cms/blogpost_list.html
  src/richie/apps/courses/templatetags/extra_tags.py
  tests/apps/courses/test_templatetags_extra_tags_order_by.py
Labels: improvement

#1274 ✨(lti-consumer) add LTI consumer plugin
  CHANGELOG.md
  env.d/development/common
  sandbox/settings.py
  setup.cfg
  src/frontend/js/components/LtiConsumer/_styles.scss
  src/frontend/js/components/LtiConsumer/index.spec.tsx
  src/frontend/js/components/LtiConsumer/index.tsx
  src/frontend/js/components/Root/index.tsx
  src/frontend/js/types/LtiConsumer.ts
  src/frontend/package.json
  src/frontend/scss/_main.scss
  src/frontend/scss/components/_subheader.scss
  src/frontend/scss/components/templates/courses/cms/_course_detail.scss
  src/frontend/scss/objects/_characteristics.scss
  src/frontend/scss/settings/_variables.scss
  src/frontend/yarn.lock
  src/richie/apps/core/templates/djangocms_video/default/video_player.html
  src/richie/apps/courses/templates/courses/cms/course_detail.html
  src/richie/plugins/lti_consumer/__init__.py
  src/richie/plugins/lti_consumer/cms_plugins.py
  src/richie/plugins/lti_consumer/defaults.py
  src/richie/plugins/lti_consumer/factories.py
  src/richie/plugins/lti_consumer/forms.py
  src/richie/plugins/lti_consumer/migrations/0001_initial.py
  src/richie/plugins/lti_consumer/migrations/__init__.py
  src/richie/plugins/lti_consumer/models.py
  src/richie/plugins/lti_consumer/static/lti_consumer/js/change_form.js
  src/richie/plugins/lti_consumer/templates/richie/lti_consumer/lti_consumer.html
  tests/apps/courses/test_templates_course_detail.py
  tests/plugins/lti_consumer/__init__.py
  tests/plugins/lti_consumer/test_cms_plugins.py
  tests/plugins/lti_consumer/test_factories.py
  tests/plugins/lti_consumer/test_forms.py
  tests/plugins/lti_consumer/test_models.py
Labels: feature, needs review

#1299 ✨(back) add protected fields to lms backends
  CHANGELOG.md
  UPGRADE.md
  sandbox/settings.py
  src/richie/apps/courses/api.py
  src/richie/apps/courses/lms/edx.py
  tests/apps/courses/test_api_course_run_sync_edx.py
Labels: improvement

#1295 ✨(search) take into account search fulltext search score for sorting
  CHANGELOG.md
  sandbox/settings.py
  src/richie/apps/search/defaults.py
  src/richie/apps/search/forms.py
  src/richie/apps/search/indexers/courses.py
  src/richie/apps/search/viewsets/courses.py
  tests/apps/search/test_autocomplete_courses.py
  tests/apps/search/test_forms_search_courses.py
  tests/apps/search/test_query_courses.py
  tests/apps/search/test_query_courses_edge_cases.py
  tests/apps/search/test_query_courses_facets.py
  tests/apps/search/test_viewsets_courses.py
Labels: feature

#1298 ✨(course_teaser) display cover image by befault
  CHANGELOG.md
  src/richie/apps/courses/settings/__init__.py
  src/richie/apps/courses/templates/courses/cms/course_detail.html
  tests/apps/courses/test_templates_course_detail.py
Labels: needs review

#1288 🔖(chore) bump version to 2.2.0
  CHANGELOG.md
  UPGRADE.md
  setup.cfg
  src/frontend/i18n/locales/ar-SA.json
  src/frontend/js/translations/ar-SA.json
  src/frontend/package.json
  src/richie/locale/ar_SA/LC_MESSAGES/django.mo
  src/richie/locale/ar_SA/LC_MESSAGES/django.po
  src/richie/locale/es_ES/LC_MESSAGES/django.mo
  src/richie/locale/es_ES/LC_MESSAGES/django.po
  src/richie/locale/fr_CA/LC_MESSAGES/django.mo
  src/richie/locale/fr_CA/LC_MESSAGES/django.po
  src/richie/locale/fr_FR/LC_MESSAGES/django.mo
  src/richie/locale/fr_FR/LC_MESSAGES/django.po
  tests_e2e/package.json
  website/package.json
  website/versioned_docs/version-2.2.0/internationalization.md
  website/versioned_sidebars/version-2.2.0-sidebars.json
  website/versions.json
Labels: FUN Team

#1303 💄(frontend) fix text selection on search input on firefox
  CHANGELOG.md
  src/frontend/scss/objects/_react-autosuggest.scss
Labels: bug

#1305 ⚡️(frontend) lazy load react widgets
  CHANGELOG.md
  src/frontend/js/components/CourseRunEnrollment/index.spec.tsx
  src/frontend/js/components/CourseRunEnrollment/index.tsx
  src/frontend/js/components/LanguageSelector/index.spec.tsx
  src/frontend/js/components/LanguageSelector/index.tsx
  src/frontend/js/components/LtiConsumer/index.spec.tsx
  src/frontend/js/components/LtiConsumer/index.tsx
  src/frontend/js/components/Root/index.spec.tsx
  src/frontend/js/components/Root/index.tsx
  src/frontend/js/components/RootSearchSuggestField/index.spec.tsx
  src/frontend/js/components/RootSearchSuggestField/index.tsx
  src/frontend/js/components/Search/index.spec.tsx
  src/frontend/js/components/Search/index.tsx
  src/frontend/js/components/SearchSuggestField/index.spec.tsx
  src/frontend/js/components/SearchSuggestField/index.tsx
  src/frontend/js/components/UserLogin/index.spec.tsx
  src/frontend/js/components/UserLogin/index.tsx
Labels: improvement

#1313 ⚡️(courses) cache getting course runs dict from the course models
  CHANGELOG.md
  src/richie/apps/courses/models/course.py
  src/richie/apps/courses/templates/courses/cms/course_detail.html
  tests/apps/courses/test_models_course.py
Labels: improvement

#1315 🔖(chore) bump version to 2.3.0
  CHANGELOG.md
  docker-compose.yml
  setup.cfg
  src/frontend/package.json
  src/richie/locale/ar_SA/LC_MESSAGES/django.po
  src/richie/locale/es_ES/LC_MESSAGES/django.po
  src/richie/locale/fr_CA/LC_MESSAGES/django.po
  src/richie/locale/fr_FR/LC_MESSAGES/django.po
  tests_e2e/package.json
  website/package.json
  website/versions.json
Labels: improvement

#1316 📝(upgrade) add instruction about the LTI consumer plugin stylesheet
  UPGRADE.md
Labels: improvement

#1318 🐛(frontend) fix lti consumer issues
  CHANGELOG.md
  src/frontend/js/components/LtiConsumer/index.tsx
Labels: bug

#1320 🔖(chore) bump version to 2.3.2
  CHANGELOG.md
  setup.cfg
  src/frontend/package.json
  tests_e2e/package.json
  website/package.json
  website/versions.json
Labels: FUN Team

#1326 🐛(course) fix pace computation
  CHANGELOG.md
  src/richie/apps/courses/models/course.py
  tests/apps/courses/test_models_course.py
Labels: bug
