Repository openfun/richie, pull requests merged in 2021-01, with the labels that each got.

#1236 ✨(development) allow connections from openedx-docker development stack
  docker-compose.yml
Labels: feature

#1241 🐛(organizations) image srcset was misconfigured
  CHANGELOG.md
  src/richie/apps/courses/templates/courses/cms/organization_detail.html
Labels: bug

#1247 🚸(PaginateCourseSearch) do not truncate pagination if it is not relevant
  CHANGELOG.md
  src/frontend/js/components/PaginateCourseSearch/index.spec.tsx
  src/frontend/js/components/PaginateCourseSearch/index.tsx
Labels: improvement

#1250 🐛(courses) fix displaying course runs in list on course detail page
  CHANGELOG.md
  src/richie/apps/courses/templates/courses/cms/fragment_course_runs_list.html
  tests/apps/courses/test_templates_course_detail.py
Labels: bug

#1251 ✨(courses) display code on course detail page with frontend editing
  CHANGELOG.md
  src/frontend/scss/components/_subheader.scss
  src/richie/apps/courses/admin.py
  src/richie/apps/courses/templates/courses/cms/course_detail.html
  tests/apps/courses/test_templates_course_detail.py
Labels: feature

#1252 ✨(courses) allow overriding a person's bio on the person plugin
  CHANGELOG.md
  src/richie/apps/courses/migrations/0027_auto_20210119_1411.py
  src/richie/apps/courses/models/person.py
  src/richie/apps/courses/templates/courses/cms/fragment_person_glimpse.html
  tests/apps/courses/test_cms_plugins_person.py
Labels: feature

#1257 🐛(plugins) fix HTMLSiteMap plugin when placed in a static placeholder
  CHANGELOG.md
  src/richie/plugins/html_sitemap/cms_plugins.py
  tests/plugins/html_sitemap/test_cms_plugins.py
Labels: bug

#1262 🐛(courses) delete orphan course run nodes
  CHANGELOG.md
  src/richie/apps/courses/migrations/0028_auto_20210126_2200.py
Labels: bug

#1265 Display 403 error when editing a course run without permission
  CHANGELOG.md
  src/richie/apps/courses/admin.py
  tests/apps/courses/test_admin_course_run.py
Labels: bug

#1266 🐛(cms_plugins) fix HTMLSiteMap plugin when current_page is not defined
  CHANGELOG.md
  src/richie/plugins/html_sitemap/cms_plugins.py
  tests/plugins/html_sitemap/test_cms_plugins.py
Labels: bug

#1268 💚(ci) fix docker login run with forks
  .circleci/config.yml
Labels: bug

#1264 🚸(frontend) hide console error in tests outputs
  CHANGELOG.md
  src/frontend/js/components/CourseRunEnrollment/index.spec.tsx
  src/frontend/js/utils/api/lms/index.spec.ts
  src/frontend/js/utils/api/lms/openedx-hawthorn.spec.ts
Labels: bug
