Repository openfun/richie, pull requests merged in 2021-06, with the labels that each got.

#1369 ✨(frontend) send username to lti consumer if he/she login
  CHANGELOG.md
  src/frontend/js/components/LtiConsumer/index.spec.tsx
  src/frontend/js/components/LtiConsumer/index.tsx
  src/frontend/js/data/useSession/index.tsx
Labels: improvement

#1371 🔧(renovate) use openfun preset
  renovate.json
Labels: dependencies

#1377 🐛(lti_consumer) fix permissions granting institutor role more carefully
  CHANGELOG.md
  src/richie/plugins/lti_consumer/api.py
  tests/plugins/lti_consumer/test_api.py
  tests/plugins/lti_consumer/test_models.py
Labels: bug

#1376 🔖(chore) bump version to 2.7.0
  CHANGELOG.md
  UPGRADE.md
  setup.cfg
  src/frontend/i18n/locales/ar-SA.json
  src/frontend/i18n/locales/es-ES.json
  src/frontend/i18n/locales/fr-CA.json
  src/frontend/i18n/locales/fr-FR.json
  src/frontend/i18n/locales/pt-PT.json
  src/frontend/js/translations/es-ES.json
  src/frontend/package.json
  src/richie/locale/ar_SA/LC_MESSAGES/django.mo
  src/richie/locale/ar_SA/LC_MESSAGES/django.po
  src/richie/locale/es_ES/LC_MESSAGES/django.mo
  src/richie/locale/es_ES/LC_MESSAGES/django.po
  src/richie/locale/fr_CA/LC_MESSAGES/django.mo
  src/richie/locale/fr_CA/LC_MESSAGES/django.po
  src/richie/locale/fr_FR/LC_MESSAGES/django.mo
  src/richie/locale/fr_FR/LC_MESSAGES/django.po
  src/richie/locale/pt_PT/LC_MESSAGES/django.mo
  src/richie/locale/pt_PT/LC_MESSAGES/django.po
  tests_e2e/package.json
  website/package.json
  website/versions.json
Labels: FUN Team

#1383 📝(richie) add documentation to connect Richie with OpenEdX
  CHANGELOG.md
  README.md
  docs/api/course-run-synchronization-api.md
  docs/displaying-connection-status.md
  docs/lms-backends.md
  docs/lms-connection.md
  docs/quick-start.md
  docs/synchronizing-course-runs.md
  docs/tls-connection.md
  sandbox/settings.py
  website/versioned_docs/version-2.0.0/lms-connection.md
  website/versioned_docs/version-2.0.1/lms-connection.md
  website/versioned_docs/version-2.5.0/lms-connection.md
Labels: docs website

#1397 🐛(frontend) fix fullscreen layout on safari
  CHANGELOG.md
  src/frontend/js/components/LtiConsumer/_styles.scss
  src/frontend/scss/components/_subheader.scss
Labels: bug
