Repository openfun/richie, pull requests merged in 2021-04, with the labels that each got.

#1327 🚸(programs) remove date on program glimpse
  CHANGELOG.md
  src/frontend/scss/objects/_program_glimpses.scss
  src/richie/apps/courses/templates/courses/cms/fragment_program_glimpse.html
Labels: improvement

#1333 🌐(all) add portugues translations
  CHANGELOG.md
  src/frontend/i18n/locales/pt-PT.json
  src/frontend/js/translations/pt-PT.json
  src/richie/locale/pt_PT/LC_MESSAGES/django.mo
  src/richie/locale/pt_PT/LC_MESSAGES/django.po
Labels: improvement

#1336 🐛(frontend) fix quality issues with <SearchFilterGroupModal />
  CHANGELOG.md
  src/frontend/js/components/SearchFilterGroupModal/_styles.scss
  src/frontend/js/components/SearchFilterGroupModal/index.tsx
Labels: bug

#1339 🐛(Search) fix filter pane quality issues on handheld devices
  CHANGELOG.md
  src/frontend/js/components/Search/index.spec.tsx
  src/frontend/js/components/Search/index.tsx
  src/frontend/scss/components/_subheader.scss
  src/frontend/scss/components/templates/search/_search.scss
Labels: bug

#1341 ✨(blogposts) add language fallback to get_related_blogposts
  CHANGELOG.md
  src/richie/apps/core/models.py
  src/richie/apps/courses/models/blog.py
  tests/apps/courses/test_models_blogpost.py
Labels: improvement

#1332 🚚(frontend) clean built frontend files before each build
  .circleci/config.yml
  CHANGELOG.md
  Dockerfile
  UPGRADE.md
  src/frontend/public-path.js
  src/frontend/webpack.config.js
  src/richie/apps/core/templates/richie/base.html
Labels: improvement

#1342 🐛(base) fix initializeAccordions compatibility issue
  CHANGELOG.md
  src/richie/apps/core/templates/richie/base.html
Labels: bug

#1346 🐛(search) avoid KeyError when a course is indexed with no titles
  CHANGELOG.md
  src/richie/apps/search/filter_definitions/courses.py
  src/richie/apps/search/indexers/categories.py
  src/richie/apps/search/indexers/courses.py
  src/richie/apps/search/indexers/organizations.py
  src/richie/apps/search/indexers/persons.py
  tests/apps/search/test_query_categories.py
  tests/apps/search/test_query_courses_edge_cases.py
  tests/apps/search/test_query_organizations.py
  tests/apps/search/test_query_persons.py
  tests/apps/search/test_viewsets_categories.py
  tests/apps/search/test_viewsets_courses.py
  tests/apps/search/test_viewsets_organizations.py
  tests/apps/search/test_viewsets_persons.py
Labels: bug

#1340 🔖(chore) bump version to 2.5.0
  CHANGELOG.md
  setup.cfg
  src/frontend/i18n/locales/ar-SA.json
  src/frontend/i18n/locales/es-ES.json
  src/frontend/i18n/locales/fr-CA.json
  src/frontend/i18n/locales/fr-FR.json
  src/frontend/i18n/locales/pt-PT.json
  src/frontend/js/translations/ar-SA.json
  src/frontend/js/translations/es-ES.json
  src/frontend/js/translations/fr-CA.json
  src/frontend/js/translations/fr-FR.json
  src/frontend/js/translations/pt-PT.json
  src/frontend/package.json
  src/richie/apps/core/defaults.py
  src/richie/locale/ar_SA/LC_MESSAGES/django.mo
  src/richie/locale/ar_SA/LC_MESSAGES/django.po
  src/richie/locale/es_ES/LC_MESSAGES/django.mo
  src/richie/locale/es_ES/LC_MESSAGES/django.po
  src/richie/locale/fr_CA/LC_MESSAGES/django.mo
  src/richie/locale/fr_CA/LC_MESSAGES/django.po
  src/richie/locale/fr_FR/LC_MESSAGES/django.mo
  src/richie/locale/fr_FR/LC_MESSAGES/django.po
  src/richie/locale/pt_PT/LC_MESSAGES/django.mo
  src/richie/locale/pt_PT/LC_MESSAGES/django.po
  tests_e2e/package.json
  website/package.json
  website/versioned_docs/version-2.5.0/lms-connection.md
  website/versions.json
  website/yarn.lock
Labels: FUN Team

#1353 🚑(LTIConsumer) fix lti context cache duration
  CHANGELOG.md
  src/richie/plugins/lti_consumer/api.py
  tests/plugins/lti_consumer/test_api.py
Labels: bug
