Repository openfun/richie, pull requests merged in 2021-11, with the labels that each got.

#1514 🚚(frontend) move type utils from utils to types directory
  CHANGELOG.md
  src/frontend/js/components/CourseRunEnrollment/index.tsx
  src/frontend/js/components/SearchFilterGroupModal/index.tsx
  src/frontend/js/components/SearchFilterValueParent/index.tsx
  src/frontend/js/components/SearchFiltersPane/index.tsx
  src/frontend/js/data/useCourseSearch/index.ts
  src/frontend/js/data/useCourseSearchParams/computeNewFilterValue.ts
  src/frontend/js/data/useCourseSearchParams/index.ts
  src/frontend/js/data/useHistory/index.tsx
  src/frontend/js/data/useSession/index.tsx
  src/frontend/js/data/useStaticFilters/index.tsx
  src/frontend/js/types/Course.ts
  src/frontend/js/types/api.ts
  src/frontend/js/types/commonDataProps.ts
  src/frontend/js/types/filters.ts
  src/frontend/js/types/index.ts
  src/frontend/js/types/utils.ts
  src/frontend/js/utils/api/authentication.ts
  src/frontend/js/utils/api/courseEnrollment.ts
  src/frontend/js/utils/api/lms/base.ts
  src/frontend/js/utils/api/lms/openedx-hawthorn.ts
  src/frontend/js/utils/useCache.ts
Labels: improvement

#1515 🐛(frontend) do not call logout twice
  CHANGELOG.md
  src/frontend/js/components/UserMenu/DesktopUserMenu.tsx
  src/frontend/js/components/UserMenu/index.spec.tsx
  src/frontend/scss/objects/_selector.scss
Labels: bug

#1521 ✨(courses) make licenses on course page optional
  CHANGELOG.md
  src/richie/apps/courses/templates/courses/cms/course_detail.html
  tests/apps/courses/test_templates_course_detail_rendering.py
Labels: improvement

#1498 ✨(courses) optional limit max archived course runs
  CHANGELOG.md
  src/frontend/scss/components/templates/courses/cms/_course_detail.scss
  src/frontend/scss/settings/_colors.scss
  src/frontend/scss/tools/_utils.scss
  src/richie/apps/core/context_processors.py
  src/richie/apps/core/templates/richie/base.html
  src/richie/apps/courses/defaults.py
  src/richie/apps/courses/templates/courses/cms/course_detail.html
  src/richie/apps/courses/templates/courses/cms/fragment_course_runs_list.html
  tests/apps/courses/test_templates_course_detail_rendering.py
Labels: improvement

#1526 🔧(frontend) use new jsx transform
  src/frontend/.eslintrc.json
  src/frontend/babel.config.js
  src/frontend/js/common/searchFields/index.tsx
  src/frontend/js/components/CourseGlimpse/CourseGlimpseFooter.tsx
  src/frontend/js/components/CourseGlimpse/index.spec.tsx
  src/frontend/js/components/CourseGlimpse/index.tsx
  src/frontend/js/components/CourseGlimpseList/index.spec.tsx
  src/frontend/js/components/CourseGlimpseList/index.tsx
  src/frontend/js/components/CourseRunEnrollment/index.spec.tsx
  src/frontend/js/components/LanguageSelector/index.spec.tsx
  src/frontend/js/components/LanguageSelector/index.tsx
  src/frontend/js/components/LtiConsumer/index.spec.tsx
  src/frontend/js/components/LtiConsumer/index.tsx
  src/frontend/js/components/Modal/index.spec.tsx
  src/frontend/js/components/Modal/index.tsx
  src/frontend/js/components/PaginateCourseSearch/index.spec.tsx
  src/frontend/js/components/PaginateCourseSearch/index.tsx
  src/frontend/js/components/Root/index.spec.tsx
  src/frontend/js/components/Root/index.tsx
  src/frontend/js/components/RootSearchSuggestField/index.spec.tsx
  src/frontend/js/components/RootSearchSuggestField/index.tsx
  src/frontend/js/components/Search/index.spec.tsx
  src/frontend/js/components/Search/index.tsx
  src/frontend/js/components/SearchFilterGroup/index.spec.tsx
  src/frontend/js/components/SearchFilterGroup/index.tsx
  src/frontend/js/components/SearchFilterGroupModal/index.spec.tsx
  src/frontend/js/components/SearchFilterGroupModal/index.tsx
  src/frontend/js/components/SearchFilterValueLeaf/index.spec.tsx
  src/frontend/js/components/SearchFilterValueLeaf/index.tsx
  src/frontend/js/components/SearchFilterValueParent/index.spec.tsx
  src/frontend/js/components/SearchFilterValueParent/index.tsx
  src/frontend/js/components/SearchFiltersPane/index.spec.tsx
  src/frontend/js/components/SearchFiltersPane/index.tsx
  src/frontend/js/components/SearchInput/index.spec.tsx
  src/frontend/js/components/SearchInput/index.tsx
  src/frontend/js/components/SearchSuggestField/index.spec.tsx
  src/frontend/js/components/SearchSuggestField/index.tsx
  src/frontend/js/components/Spinner/index.tsx
  src/frontend/js/components/UserLogin/index.spec.tsx
  src/frontend/js/components/UserLogin/index.tsx
  src/frontend/js/components/UserMenu/DesktopUserMenu.tsx
  src/frontend/js/components/UserMenu/MobileUserMenu.tsx
  src/frontend/js/components/UserMenu/index.spec.tsx
  src/frontend/js/components/UserMenu/index.tsx
  src/frontend/js/data/useCourseSearch/index.spec.tsx
  src/frontend/js/data/useCourseSearchParams/index.spec.tsx
  src/frontend/js/data/useEnrollment/index.spec.tsx
  src/frontend/js/data/useFilterValue/index.spec.tsx
  src/frontend/js/data/useHistory/index.spec.tsx
  src/frontend/js/data/useHistory/index.tsx
  src/frontend/js/data/useSession/index.spec.tsx
  src/frontend/js/data/useSession/index.tsx
  src/frontend/js/index.tsx
  src/frontend/package.json
  src/frontend/yarn.lock
Labels: improvement, dependencies

#1527 🐛(opengraph) fix og:image
  CHANGELOG.md
  src/richie/apps/core/context_processors.py
  tests/apps/courses/test_templates_course_detail_opengraph.py
Labels: bug

#1529 💄(frontend) add theme modifier to spinner
  CHANGELOG.md
  UPGRADE.md
  src/frontend/js/components/Spinner/_styles.scss
  src/frontend/js/components/Spinner/index.tsx
  src/frontend/scss/settings/_colors.scss
Labels: improvement
