Repository openfun/richie, pull requests merged in 2021-08, with the labels that each got.

#1410 ⬆️(cms) upgrade DjangoCMS to version 3.9.0 and Django to version 3.2.6
  CHANGELOG.md
  renovate.json
  setup.cfg
Labels: improvement

#1414 ✨(blogposts) sort related blog posts by their publication date
  CHANGELOG.md
  src/richie/apps/courses/models/blog.py
  tests/apps/courses/test_models_blogpost.py
Labels: improvement

#1412 🐛(search) fix search bug due to wrong ordering of char filters
  CHANGELOG.md
  src/richie/apps/search/text_indexing.py
  tests/apps/search/test_partial_mappings.py
  tests/apps/search/test_query_courses_edge_cases.py
Labels: bug

#1416 ✨(search) add introduction text to search index and API
  CHANGELOG.md
  src/richie/apps/search/forms.py
  src/richie/apps/search/indexers/courses.py
  tests/apps/search/test_forms_search_courses.py
  tests/apps/search/test_indexers_courses.py
  tests/apps/search/test_query_courses.py
  tests/apps/search/test_query_courses_edge_cases.py
  tests/apps/search/test_viewsets_courses.py
Labels: feature

#1418 🧐(search) boost title field for a better search experience
  CHANGELOG.md
  src/richie/apps/search/forms.py
  tests/apps/search/test_forms_search_courses.py
  tests/apps/search/test_query_courses_edge_cases.py
Labels: feature

#1423 🐛(courses) hide unpublished pages from related objects on public page
  CHANGELOG.md
  src/richie/apps/core/models.py
  tests/apps/courses/test_models_category.py
  tests/apps/courses/test_models_course.py
  tests/apps/courses/test_models_organization.py
  tests/apps/courses/test_models_person.py
Labels: bug

#1427 🐛(blogposts) fix section on blogpost detail page
  CHANGELOG.md
  src/frontend/scss/components/templates/courses/cms/_blogpost_detail.scss
Labels: bug

#1426 ✅(search) clarify languages used on course unpublished in a language
  tests/apps/search/test_indexers_courses.py
Labels: FUN Team

#1405 🔍️(SEO) add sitemap to robots
  CHANGELOG.md
  sandbox/urls.py
  src/richie/apps/core/templates/richie/robots.html
  tests/apps/core/test_robots.py
Labels: improvement

#1399 Add Google Analytics using Google Tag manager script.
  CHANGELOG.md
  docs/web-analytics.md
  sandbox/settings.py
  src/richie/apps/core/context_processors.py
  src/richie/apps/core/templates/richie/base.html
  src/richie/apps/core/templates/richie/web_analytics.html
  src/richie/apps/courses/models/organization.py
  tests/apps/core/test_web_analytics.py
  tests/apps/courses/test_models_organization.py
Labels: feature
