Repository openfun/richie, pull requests merged in 2021-10, with the labels that each got.

#1471 💄(subheader) use a dedicated variable to set aside column width
  CHANGELOG.md
  UPGRADE.md
  src/frontend/scss/components/_subheader.scss
  src/frontend/scss/settings/_variables.scss
Labels: bug

#1472 🐛(courses) fix "pt_effort" string computation when effort is not set
  CHANGELOG.md
  src/richie/apps/courses/models/course.py
  tests/apps/courses/test_models_course.py
Labels: bug

#1469 📝(UPGRADE) add missing instruction from 2.7.x to 2.8.x
  UPGRADE.md
Labels: docs website

#1473 🔖(chore) bump release to version 2.8.2
  CHANGELOG.md
  setup.cfg
  src/frontend/package.json
  src/richie/locale/ar_SA/LC_MESSAGES/django.mo
  src/richie/locale/ar_SA/LC_MESSAGES/django.po
  src/richie/locale/es_ES/LC_MESSAGES/django.mo
  src/richie/locale/es_ES/LC_MESSAGES/django.po
  src/richie/locale/fr_CA/LC_MESSAGES/django.mo
  src/richie/locale/fr_CA/LC_MESSAGES/django.po
  src/richie/locale/fr_FR/LC_MESSAGES/django.mo
  src/richie/locale/fr_FR/LC_MESSAGES/django.po
  src/richie/locale/pt_PT/LC_MESSAGES/django.mo
  src/richie/locale/pt_PT/LC_MESSAGES/django.po
  tests_e2e/package.json
  website/package.json
  website/versions.json
Labels: FUN Team
