Repository openfun/richie, pull requests merged in 2022-11, with the labels that each got.

#1820 ✅(frontend) fix flaky tests
  src/frontend/js/utils/CreditCardHelper/index.spec.tsx
Labels: bug

#1824 🐛(frontend) fix courses badges css
  CHANGELOG.md
  src/frontend/scss/objects/_course_glimpses.scss
Labels: needs review, bug

#1833 ✨(api) allow bulk course run synchronization
  CHANGELOG.md
  src/richie/apps/courses/api.py
  src/richie/apps/courses/exceptions.py
  src/richie/apps/courses/urls.py
  tests/apps/courses/test_api_course_run_sync.py
Labels: feature

#1832 🐛(courses) fix course page style in edit mode
  CHANGELOG.md
  src/frontend/scss/components/templates/courses/cms/_course_detail.scss
Labels: bug

#1836 🔨(bin) stop using env variable to activate sites
  cookiecutter/{{cookiecutter.organization}}-richie-site-factory/.circleci/src/commands/generate-version-file.yml
  cookiecutter/{{cookiecutter.organization}}-richie-site-factory/Dockerfile
  cookiecutter/{{cookiecutter.organization}}-richie-site-factory/Makefile
  cookiecutter/{{cookiecutter.organization}}-richie-site-factory/bin/_config.sh
  cookiecutter/{{cookiecutter.organization}}-richie-site-factory/bin/activate
  cookiecutter/{{cookiecutter.organization}}-richie-site-factory/bin/add-site
  cookiecutter/{{cookiecutter.organization}}-richie-site-factory/docker-compose.yml
  cookiecutter/{{cookiecutter.organization}}-richie-site-factory/docker/files/usr/local/bin/entrypoint
  cookiecutter/{{cookiecutter.organization}}-richie-site-factory/docs/aws.md
  cookiecutter/{{cookiecutter.organization}}-richie-site-factory/template/{{cookiecutter.site}}/src/backend/base/tests/test_cache.py
  cookiecutter/{{cookiecutter.organization}}-richie-site-factory/template/{{cookiecutter.site}}/src/backend/{{cookiecutter.site}}/wsgi.py
Labels: scaffolding
