Repository openfun/richie, pull requests merged in 2022-08, with the labels that each got.

#1756 📌(backend) pin all python dependencies
  setup.cfg
Labels: dependencies

#1759 👽(frontend) add language field into the claim of fake jwt token
  src/frontend/js/utils/api/lms/dummy.ts
Labels: javascript

#1762 🔖(chore) bump to version 2.15.1
  CHANGELOG.md
  cookiecutter/{{cookiecutter.organization}}-richie-site-factory/template/{{cookiecutter.site}}/requirements/base.txt
  cookiecutter/{{cookiecutter.organization}}-richie-site-factory/template/{{cookiecutter.site}}/src/frontend/package.json
  setup.cfg
  src/frontend/package.json
  src/richie/locale/fr_CA/LC_MESSAGES/django.mo
  src/richie/locale/fr_CA/LC_MESSAGES/django.po
  tests_e2e/package.json
  website/package.json
  website/versioned_docs/version-2.15.1/accessibility-testing.md
  website/versioned_docs/version-2.15.1/api/course-run-synchronization-api.md
  website/versioned_docs/version-2.15.1/assets/images/crowdin-join-richie.gif
  website/versioned_docs/version-2.15.1/assets/images/demo-screenshot.jpg
  website/versioned_docs/version-2.15.1/building-the-frontend.md
  website/versioned_docs/version-2.15.1/contributing.md
  website/versioned_docs/version-2.15.1/cookiecutter.md
  website/versioned_docs/version-2.15.1/css-guidelines.md
  website/versioned_docs/version-2.15.1/discover.md
  website/versioned_docs/version-2.15.1/displaying-connection-status.md
  website/versioned_docs/version-2.15.1/django-react-interop.md
  website/versioned_docs/version-2.15.1/docker-development.md
  website/versioned_docs/version-2.15.1/frontend-overrides.md
  website/versioned_docs/version-2.15.1/installation.md
  website/versioned_docs/version-2.15.1/internationalization.md
  website/versioned_docs/version-2.15.1/joanie-connection.md
  website/versioned_docs/version-2.15.1/lms-backends.md
  website/versioned_docs/version-2.15.1/lms-connection.md
  website/versioned_docs/version-2.15.1/native-installation.md
  website/versioned_docs/version-2.15.1/synchronizing-course-runs.md
  website/versioned_docs/version-2.15.1/tls-connection.md
  website/versioned_docs/version-2.15.1/web-analytics.md
  website/versioned_sidebars/version-2.15.1-sidebars.json
  website/versions.json
Labels: FUN Team

#1709 Improve accessibility on filters pane when using a small screen
  CHANGELOG.md
  src/frontend/js/components/Search/FiltersPaneCloseButton.tsx
  src/frontend/js/components/Search/index.spec.tsx
  src/frontend/js/components/Search/index.tsx
  src/frontend/js/components/SearchFiltersPane/index.tsx
  src/frontend/scss/components/templates/search/_search.scss
Labels: a11y
