Repository openfun/richie, pull requests merged in 2022-09, with the labels that each got.

#1753 ⚡️(dns) add dns prefetch for media cdn
  CHANGELOG.md
  cookiecutter/{{cookiecutter.organization}}-richie-site-factory/template/{{cookiecutter.site}}/src/backend/{{cookiecutter.site}}/settings.py
  sandbox/settings.py
  src/richie/apps/core/context_processors.py
  src/richie/apps/core/templates/richie/base.html
  tests/apps/core/test_templates_dns_prefetch.py
Labels: improvement

#1772 🐛(frontend) fix flaky tests using random currencies
  src/frontend/js/components/SaleTunnelStepPayment/index.spec.tsx
  src/frontend/js/components/SaleTunnelStepValidation/index.spec.tsx
Labels: bug

#1773 📌(backend) unpin python dependencies
  setup.cfg
Labels: dependencies

#1774 🧑‍💻(frontend) add components to storybook
  CHANGELOG.md
  src/frontend/.storybook/main.js
  src/frontend/.storybook/preview-body.html
  src/frontend/.storybook/preview.js
  src/frontend/.storybook/preview.tsx
  src/frontend/js/components/Banner/index.stories.tsx
  src/frontend/js/components/Form/CheckboxField.stories.tsx
  src/frontend/js/components/Form/Field.stories.tsx
  src/frontend/js/components/Form/RadioField.stories.tsx
  src/frontend/js/components/Form/SelectField.stories.tsx
  src/frontend/js/components/Form/TextAreaField.stories.tsx
  src/frontend/js/components/Form/TextField.stories.tsx
  src/frontend/js/components/Icon/index.stories.tsx
  src/frontend/js/components/Modal/index.stories.tsx
Labels: needs review, feature

#1777 🔖(chore) bump to version 2.16.0
  CHANGELOG.md
  cookiecutter/{{cookiecutter.organization}}-richie-site-factory/template/{{cookiecutter.site}}/requirements/base.txt
  cookiecutter/{{cookiecutter.organization}}-richie-site-factory/template/{{cookiecutter.site}}/src/frontend/package.json
  setup.cfg
  src/frontend/package.json
  src/richie/locale/ar_SA/LC_MESSAGES/django.mo
  src/richie/locale/ar_SA/LC_MESSAGES/django.po
  src/richie/locale/es_ES/LC_MESSAGES/django.mo
  src/richie/locale/es_ES/LC_MESSAGES/django.po
  src/richie/locale/fr_CA/LC_MESSAGES/django.mo
  src/richie/locale/fr_CA/LC_MESSAGES/django.po
  src/richie/locale/fr_FR/LC_MESSAGES/django.mo
  src/richie/locale/fr_FR/LC_MESSAGES/django.po
  src/richie/locale/pt_PT/LC_MESSAGES/django.mo
  src/richie/locale/pt_PT/LC_MESSAGES/django.po
  src/richie/locale/ru_RU/LC_MESSAGES/django.mo
  src/richie/locale/ru_RU/LC_MESSAGES/django.po
  tests_e2e/package.json
  website/package.json
  website/versioned_docs/version-2.16.0/accessibility-testing.md
  website/versioned_docs/version-2.16.0/api/course-run-synchronization-api.md
  website/versioned_docs/version-2.16.0/assets/images/crowdin-join-richie.gif
  website/versioned_docs/version-2.16.0/assets/images/demo-screenshot.jpg
  website/versioned_docs/version-2.16.0/building-the-frontend.md
  website/versioned_docs/version-2.16.0/contributing.md
  website/versioned_docs/version-2.16.0/cookiecutter.md
  website/versioned_docs/version-2.16.0/css-guidelines.md
  website/versioned_docs/version-2.16.0/discover.md
  website/versioned_docs/version-2.16.0/displaying-connection-status.md
  website/versioned_docs/version-2.16.0/django-react-interop.md
  website/versioned_docs/version-2.16.0/docker-development.md
  website/versioned_docs/version-2.16.0/frontend-overrides.md
  website/versioned_docs/version-2.16.0/installation.md
  website/versioned_docs/version-2.16.0/internationalization.md
  website/versioned_docs/version-2.16.0/joanie-connection.md
  website/versioned_docs/version-2.16.0/lms-backends.md
  website/versioned_docs/version-2.16.0/lms-connection.md
  website/versioned_docs/version-2.16.0/native-installation.md
  website/versioned_docs/version-2.16.0/synchronizing-course-runs.md
  website/versioned_docs/version-2.16.0/tls-connection.md
  website/versioned_docs/version-2.16.0/web-analytics.md
  website/versioned_sidebars/version-2.16.0-sidebars.json
  website/versions.json
Labels: FUN Team

#1776 Cookiecutter/add job to check template consistency
  .circleci/config.yml
Labels: improvement

#1782 🐛(admin) order languages choices in course run admin form
  CHANGELOG.md
  src/richie/apps/courses/admin.py
  tests/apps/courses/test_admin_form_course_run.py
Labels: bug

#1763 ♿️(templates) add label on external video players
  CHANGELOG.md
  src/richie/apps/core/templates/djangocms_video/default/video_player.html
  tests/apps/courses/test_templates_course_detail_rendering.py
Labels: a11y

#1792 💚(cookiecutter) exec cookiecutter-bootstrap job only on release branch
  .circleci/config.yml
Labels: improvement
