Repository openfun/richie, pull requests merged in 2022-03, with the labels that each got.

#1629 🐛(layout) fix section tile title with richtext
  CHANGELOG.md
  src/richie/plugins/section/templates/richie/section/section_tiles.html
  tests/plugins/section/test_templates_section_default.py
Labels: bug

#1631 🐛(layout) display author name in blogpost detail in published mode also
  CHANGELOG.md
  src/richie/apps/courses/templates/courses/cms/blogpost_detail.html
  tests/apps/courses/test_templates_blogpost_detail.py
Labels: bug

#1632 ✨(courses) add 'excerpt' placeholder to Organization detail template
  CHANGELOG.md
  src/frontend/scss/objects/_organization_glimpses.scss
  src/richie/apps/courses/settings/__init__.py
  src/richie/apps/courses/templates/courses/cms/fragment_organization_glimpse.html
  src/richie/apps/courses/templates/courses/cms/organization_detail.html
  tests/apps/courses/test_templates_organization_detail.py
Labels: bug, work in progress

#1640 💄(layout) set font size to 1rem on some detail pages body contents
  CHANGELOG.md
  src/frontend/scss/components/templates/courses/cms/_organization_detail.scss
  src/frontend/scss/components/templates/courses/cms/_person_detail.scss
  src/frontend/scss/components/templates/courses/cms/_program_detail.scss
Labels: improvement

#1638 🐛(course) fix course run deletion when translation title is empty
  CHANGELOG.md
  src/richie/apps/courses/models/course.py
  tests/apps/courses/test_models_course_run.py
Labels: bug

#1648 ♿️(templates) improve template rendering
  CHANGELOG.md
  src/frontend/js/components/CourseGlimpse/index.tsx
  src/richie/apps/core/templates/richie/base.html
  src/richie/apps/core/templates/social-networks/blogpost-badges.html
  src/richie/apps/core/templates/social-networks/course-badges.html
  src/richie/apps/core/templates/social-networks/footer-badges.html
  src/richie/apps/courses/templates/courses/cms/fragment_category_glimpse.html
  src/richie/apps/courses/templates/courses/cms/fragment_course_glimpse.html
  src/richie/apps/courses/templates/courses/cms/fragment_error_detail_template_banner.html
  src/richie/plugins/glimpse/templates/richie/glimpse/glimpse_quote.html
  tests/apps/courses/test_cms_plugins_course.py
  tests/apps/courses/test_templates_category_detail.py
  tests/apps/courses/test_templates_course_detail_rendering.py
  tests/apps/courses/test_templates_organization_detail.py
  tests/apps/courses/test_templates_person_detail.py
  tests/apps/courses/test_templates_program_detail.py
Labels: a11y

#1645 ♿️(styles) improve the offscreen class
  CHANGELOG.md
  src/frontend/scss/generic/_accessibility.scss
  src/richie/apps/core/templates/richie/base.html
Labels: a11y

#1662 🚑(frontend) make useCourseSearch hook locale sensible
  CHANGELOG.md
  src/frontend/js/data/useCourseSearch/index.spec.tsx
  src/frontend/js/data/useCourseSearch/index.ts
Labels: critical, bug

#1655 💄(course_glimpse) fix style with narrow org logo
  CHANGELOG.md
  src/frontend/scss/objects/_course_glimpses.scss
Labels: bug, easy pick
