Repository openfun/richie, pull requests merged in 2022-01, with the labels that each got.

#1558 🎨(core) make brand link customizable & rename related template block
  CHANGELOG.md
  UPGRADE.md
  src/richie/apps/core/templates/richie/base.html
Labels: improvement

#1559 🔖(chore) bump release to version 2.11.0
  CHANGELOG.md
  UPGRADE.md
  setup.cfg
  src/frontend/package.json
  tests_e2e/package.json
  website/package.json
  website/versions.json
Labels: FUN Team, improvement

#1561 🐛(lti_consumer) Add missing language parameter in LTI requests
  CHANGELOG.md
  src/richie/plugins/lti_consumer/api.py
  src/richie/plugins/lti_consumer/models.py
  tests/plugins/lti_consumer/test_api.py
  tests/plugins/lti_consumer/test_models.py
Labels: bug

#1569 💄(frontend) improve course glimpse layout
  CHANGELOG.md
  src/frontend/js/components/CourseGlimpse/index.spec.tsx
  src/frontend/js/components/CourseGlimpse/index.tsx
  src/frontend/scss/objects/_course_glimpses.scss
  src/richie/apps/courses/templates/courses/cms/fragment_course_glimpse.html
  tests/apps/courses/test_cms_plugins_course.py
Labels: improvement

#1549 ✨(course) add course run catalog visibility
  CHANGELOG.md
  src/frontend/scss/colors/_theme.scss
  src/frontend/scss/components/templates/courses/cms/_course_detail.scss
  src/richie/apps/courses/admin.py
  src/richie/apps/courses/api.py
  src/richie/apps/courses/lms/edx.py
  src/richie/apps/courses/migrations/0033_auto_20211207_2251.py
  src/richie/apps/courses/models/course.py
  src/richie/apps/courses/serializers.py
  src/richie/apps/courses/static/richie/images/catalog_visibility/course_only.svg
  src/richie/apps/courses/static/richie/images/catalog_visibility/hidden.svg
  src/richie/apps/courses/templates/courses/cms/fragment_course_run.html
  src/richie/apps/courses/templates/courses/cms/fragment_course_runs_list.html
  src/richie/apps/search/indexers/courses.py
  tests/apps/courses/test_admin_course_run.py
  tests/apps/courses/test_admin_form_course_run.py
  tests/apps/courses/test_api_course_run_sync_edx.py
  tests/apps/courses/test_models_course_run.py
  tests/apps/courses/test_templates_course_detail_rendering.py
  tests/apps/search/test_indexers_courses.py
Labels: feature

#1574 Edited homepage language
  website/pages/en/index.js
Labels: docs website

#1576 📌(backend) remove use of forked djangocms-admin-style
  Dockerfile
Labels: dependencies
