Repository openfun/richie, pull requests merged in 2022-02, with the labels that each got.

#1583 ✨(frontend) Create a Banner React component
  CHANGELOG.md
  src/frontend/js/components/Banner/index.spec.tsx
  src/frontend/js/components/Banner/index.tsx
Labels: improvement

#1580 🐛(courses) hide unpublished objects from list views
  CHANGELOG.md
  src/richie/apps/courses/templates/courses/cms/category_list.html
  src/richie/apps/courses/templates/courses/cms/organization_list.html
  src/richie/apps/courses/templates/courses/cms/person_list.html
  src/richie/apps/courses/templates/courses/cms/program_list.html
  tests/apps/courses/test_templates_category_list.py
  tests/apps/courses/test_templates_person_list.py
  tests/apps/courses/test_templates_program_list.py
Labels: bug

#1585 🔖(chore) bump release to version 2.12.0
  CHANGELOG.md
  setup.cfg
  src/frontend/i18n/locales/ar-SA.json
  src/frontend/i18n/locales/es-ES.json
  src/frontend/i18n/locales/fr-CA.json
  src/frontend/i18n/locales/fr-FR.json
  src/frontend/i18n/locales/pt-PT.json
  src/frontend/i18n/locales/ru-RU.json
  src/frontend/js/translations/ar-SA.json
  src/frontend/js/translations/es-ES.json
  src/frontend/js/translations/fr-CA.json
  src/frontend/js/translations/fr-FR.json
  src/frontend/js/translations/pt-PT.json
  src/frontend/js/translations/ru-RU.json
  src/frontend/package.json
  src/richie/locale/ar_SA/LC_MESSAGES/django.mo
  src/richie/locale/ar_SA/LC_MESSAGES/django.po
  src/richie/locale/es_ES/LC_MESSAGES/django.mo
  src/richie/locale/es_ES/LC_MESSAGES/django.po
  src/richie/locale/fr_CA/LC_MESSAGES/django.mo
  src/richie/locale/fr_CA/LC_MESSAGES/django.po
  src/richie/locale/fr_FR/LC_MESSAGES/django.mo
  src/richie/locale/fr_FR/LC_MESSAGES/django.po
  src/richie/locale/pt_PT/LC_MESSAGES/django.mo
  src/richie/locale/pt_PT/LC_MESSAGES/django.po
  src/richie/locale/ru_RU/LC_MESSAGES/django.mo
  src/richie/locale/ru_RU/LC_MESSAGES/django.po
  tests_e2e/package.json
  website/package.json
  website/versions.json
Labels: FUN Team

#1595 👷(tests) fix tests for mysql
  env.d/development/mysql
Labels: bug

#1593 ⬆️(mysql) upgrade mysql to version 8
  .circleci/config.yml
  CHANGELOG.md
  docker-compose.yml
Labels: dependencies

#1590 🚸(course) add admin autocomplete feature on Page select in Person plugin
  CHANGELOG.md
  sandbox/settings.py
  setup.cfg
  src/richie/apps/courses/cms_plugins.py
  src/richie/apps/courses/forms.py
  src/richie/apps/courses/urls.py
  src/richie/apps/courses/views.py
  tests/apps/courses/test_cms_views_person.py
Labels: improvement

#1600 ♻️(frontend) use createWebStoragePersistor
  CHANGELOG.md
  src/frontend/js/data/SessionProvider/index.spec.tsx
  src/frontend/js/utils/react-query/createQueryClient.ts
  src/frontend/js/utils/react-query/createSessionStoragePersistor/index.spec.ts
  src/frontend/js/utils/react-query/createSessionStoragePersistor/index.ts
Labels: improvement

#1601 🚸(courses) add admin autocomplete for remaining page related plugins
  CHANGELOG.md
  src/richie/apps/courses/cms_plugins.py
  src/richie/apps/courses/forms.py
  src/richie/apps/courses/urls.py
  src/richie/apps/courses/views.py
  tests/apps/courses/test_cms_views.py
Labels: improvement

#1584 ✨(web_analytics) improve web analytics
  CHANGELOG.md
  docs/web-analytics.md
  src/frontend/js/data/useCourseEnrollment/index.ts
  src/frontend/js/types/WebAnalytics.ts
  src/frontend/js/types/commonDataProps.ts
  src/frontend/js/types/web-analytics/google_analytics.d.ts
  src/frontend/js/types/web-analytics/google_tag_manager.d.ts
  src/frontend/js/utils/api/web-analytics/base.ts
  src/frontend/js/utils/api/web-analytics/google_analytics.spec.ts
  src/frontend/js/utils/api/web-analytics/google_analytics.ts
  src/frontend/js/utils/api/web-analytics/google_tag_manager.spec.ts
  src/frontend/js/utils/api/web-analytics/google_tag_manager.ts
  src/frontend/js/utils/api/web-analytics/index.ts
  src/frontend/js/utils/api/web-analytics/no_provider.spec.ts
  src/frontend/js/utils/api/web-analytics/unknown_provider.spec.ts
  src/frontend/js/utils/test/factories.ts
  src/richie/apps/core/context_processors.py
  src/richie/apps/core/templates/richie/web_analytics.html
  tests/apps/core/test_pages.py
  tests/apps/core/test_web_analytics.py
Labels: feature

#1603 🔖(chore) bump release to version 2.13.0
  CHANGELOG.md
  setup.cfg
  src/frontend/package.json
  src/richie/locale/ar_SA/LC_MESSAGES/django.mo
  src/richie/locale/ar_SA/LC_MESSAGES/django.po
  src/richie/locale/es_ES/LC_MESSAGES/django.mo
  src/richie/locale/es_ES/LC_MESSAGES/django.po
  src/richie/locale/fr_CA/LC_MESSAGES/django.mo
  src/richie/locale/fr_CA/LC_MESSAGES/django.po
  src/richie/locale/fr_FR/LC_MESSAGES/django.mo
  src/richie/locale/fr_FR/LC_MESSAGES/django.po
  src/richie/locale/pt_PT/LC_MESSAGES/django.mo
  src/richie/locale/pt_PT/LC_MESSAGES/django.po
  src/richie/locale/ru_RU/LC_MESSAGES/django.mo
  src/richie/locale/ru_RU/LC_MESSAGES/django.po
  tests_e2e/package.json
  website/package.json
  website/versions.json
Labels: FUN Team

#1609 🔧(frontend) allow overriding of any module
  .circleci/config.yml
  CHANGELOG.md
  UPGRADE.md
  src/frontend/webpack.config.js
Labels: improvement

#1617 ♿️(search) add labels to search suggest fields for screen readers
  CHANGELOG.md
  src/frontend/js/components/RootSearchSuggestField/index.spec.tsx
  src/frontend/js/components/RootSearchSuggestField/index.tsx
  src/frontend/js/components/SearchSuggestField/index.spec.tsx
  src/frontend/js/components/SearchSuggestField/index.tsx
Labels: a11y

#1618 ♿️(search) add a heading for the search results
  CHANGELOG.md
  src/frontend/js/components/Search/index.tsx
Labels: a11y
