Repository openfun/richie, pull requests merged in 2022-04, with the labels that each got.

#1664 🍱(fonts) self-host webfonts hind and montserrat
  CHANGELOG.md
  src/frontend/scss/settings/_fonts.scss
  src/richie/apps/core/static/richie/fonts/hind/hind-regular.woff
  src/richie/apps/core/static/richie/fonts/hind/hind-regular.woff2
  src/richie/apps/core/static/richie/fonts/hind/hind-semibold.woff
  src/richie/apps/core/static/richie/fonts/hind/hind-semibold.woff2
  src/richie/apps/core/static/richie/fonts/montserrat/montserrat-bold.woff
  src/richie/apps/core/static/richie/fonts/montserrat/montserrat-bold.woff2
  src/richie/apps/core/static/richie/fonts/montserrat/montserrat-extrabold.woff
  src/richie/apps/core/static/richie/fonts/montserrat/montserrat-extrabold.woff2
  src/richie/apps/core/static/richie/fonts/montserrat/montserrat-light.woff
  src/richie/apps/core/static/richie/fonts/montserrat/montserrat-light.woff2
  src/richie/apps/core/static/richie/fonts/montserrat/montserrat-medium.woff
  src/richie/apps/core/static/richie/fonts/montserrat/montserrat-medium.woff2
Labels: dependencies

#1668 🐛(frontend) clear session on login and register
  CHANGELOG.md
  src/frontend/js/data/SessionProvider/BaseSessionProvider.tsx
  src/frontend/js/data/SessionProvider/JoanieSessionProvider.spec.tsx
  src/frontend/js/data/SessionProvider/JoanieSessionProvider.tsx
  src/frontend/js/data/SessionProvider/index.spec.tsx
Labels: bug

#1671 💄(frontend) prevent course glimpse title color override
  CHANGELOG.md
  src/frontend/scss/objects/_course_glimpses.scss
Labels: bug

#1674 🚑(frontend) fix search query string formatting
  CHANGELOG.md
  src/frontend/js/components/SearchFilterGroupModal/index.spec.tsx
  src/frontend/js/data/getResourceList/index.ts
Labels: bug

#1675 🚑(frontend) preserve query string on language change
  CHANGELOG.md
  src/frontend/js/components/LanguageSelector/index.spec.tsx
  src/frontend/js/components/LanguageSelector/index.tsx
Labels: bug

#1676 🔖(chore) bump to version 2.14.1
  CHANGELOG.md
  setup.cfg
  src/frontend/package.json
  tests_e2e/package.json
  website/package.json
  website/versions.json
Labels: FUN Team

#1679 ✅(frontend) fix erratic failure
  CHANGELOG.md
  src/frontend/js/components/SaleTunnelStepPayment/index.spec.tsx
  src/frontend/js/components/SaleTunnelStepPayment/index.tsx
Labels: bug

#1683 💄(frontend) improve sale tunnel overriding
  CHANGELOG.md
  UPGRADE.md
  src/frontend/js/components/AddressesManagement/AddressForm.tsx
  src/frontend/js/components/AddressesManagement/_styles.scss
  src/frontend/js/components/AddressesManagement/index.tsx
  src/frontend/js/components/PaymentButton/index.tsx
  src/frontend/js/components/RegisteredAddress/_styles.scss
  src/frontend/js/components/RegisteredAddress/index.tsx
  src/frontend/js/components/SaleTunnel/_styles.scss
  src/frontend/js/components/SaleTunnelStepPayment/index.tsx
  src/frontend/js/components/SaleTunnelStepResume/index.tsx
  src/frontend/js/components/SaleTunnelStepValidation/index.tsx
  src/frontend/scss/_main.scss
  src/frontend/scss/colors/_theme.scss
  src/frontend/scss/tools/_buttons.scss
  src/frontend/scss/tools/_colors.scss
Labels: improvement

#1686 🐛(renovate) fix renovate configuration
  renovate.json
Labels: bug

#1688 📝(website) fix and improve website documentation
  README.md
  docs/assets/images/demo-screenshot.jpg
  docs/cookiecutter.md
  docs/discover.md
  docs/native-installation.md
  website/core/Footer.js
  website/pages/en/help.js
  website/pages/en/index.js
  website/pages/en/versions.js
  website/siteConfig.js
  website/versioned_docs/version-1.12/native-installation.md
  website/versioned_docs/version-1.12/quick-start.md
  website/versioned_docs/version-2.0.0/native-installation.md
  website/versioned_docs/version-2.0.0/quick-start.md
  website/versioned_docs/version-2.8.0/quick-start.md
  website/versioned_sidebars/version-1.12-sidebars.json
  website/versioned_sidebars/version-1.13-sidebars.json
  website/versioned_sidebars/version-1.16-sidebars.json
  website/versioned_sidebars/version-2.0.0-sidebars.json
  website/versioned_sidebars/version-2.2.0-sidebars.json
  website/versioned_sidebars/version-2.8.1-sidebars.json
Labels: docs website

#1690 📝(website) add option to run Cookiecutter from Docker
  docs/cookiecutter.md
Labels: docs website
