Repository openfun/richie, pull requests merged in 2022-12, with the labels that each got.

#1841 💚(ci) fix cookiecutter-bootstrap job
  .circleci/config.yml
Labels: bug

#1842 🧑‍💻(github) improve bug report issue template
  .github/ISSUE_TEMPLATE/Bug_report.md
Labels: FUN Team

#1843 💄(course-detail) fix course run visibility state icon position
  src/frontend/scss/components/templates/courses/cms/_course_detail.scss
Labels: bug

#1846 ♻️(frontend) use versionned Joanie API routes
  CHANGELOG.md
  sandbox/settings.py
  src/frontend/js/components/AddressesManagement/index.spec.tsx
  src/frontend/js/components/CourseProductCertificateItem/index.spec.tsx
  src/frontend/js/components/CourseProductCourseRuns/index.spec.tsx
  src/frontend/js/components/CourseProductsList/index.spec.tsx
  src/frontend/js/components/Dashboard/index.spec.tsx
  src/frontend/js/components/DashboardAddressesManagement/DashboardCreateAddress.spec.tsx
  src/frontend/js/components/DashboardAddressesManagement/DashboardEditAddress.spec.tsx
  src/frontend/js/components/DashboardAddressesManagement/index.spec.tsx
  src/frontend/js/components/DashboardCreditCardsManagement/DashboardEditCreditCard.spec.tsx
  src/frontend/js/components/DashboardCreditCardsManagement/index.spec.tsx
  src/frontend/js/components/PaymentButton/index.spec.tsx
  src/frontend/js/components/SaleTunnel/index.spec.tsx
  src/frontend/js/components/SaleTunnelStepPayment/index.spec.tsx
  src/frontend/js/data/SessionProvider/JoanieSessionProvider.spec.tsx
  src/frontend/js/data/useCourseEnrollment/index.spec.tsx
  src/frontend/js/hooks/useCreditCards/index.spec.tsx
  src/frontend/js/settings.ts
  src/frontend/js/utils/api/joanie.ts
Labels: feature
