Repository openfun/richie, pull requests merged in 2023-01, with the labels that each got.

#1870 🐛(frontend) Bug/error message course run item
  CHANGELOG.md
  src/frontend/js/components/CourseProductCourseRuns/EnrollableCourseRunList.tsx
  src/frontend/js/components/CourseProductCourseRuns/EnrolledCourseRun.tsx
  src/frontend/js/components/CourseProductCourseRuns/_styles.scss
  src/frontend/js/components/CourseProductCourseRuns/index.spec.tsx
  src/frontend/js/components/PaymentButton/_styles.scss
Labels: improvement

#1873 🐛(frontend) show message when a product without any course run
  CHANGELOG.md
  src/frontend/js/components/CourseProductItem/_styles.scss
  src/frontend/js/components/SaleTunnel/index.spec.tsx
  src/frontend/js/components/SaleTunnel/index.tsx
Labels: improvement

#1882 📝(doc) update joanie-connection documentation
  CHANGELOG.md
  UPGRADE.md
  docs/joanie-connection.md
Labels: docs website

#1885 ♿(frontend) use darker color for empty course detail
  CHANGELOG.md
  src/frontend/scss/colors/_theme.scss
Labels: a11y

#1886 🐛(frontend) fix omniscient stale query that stay empty
  src/frontend/js/hooks/useResources/useResourcesOmniscient.ts
Labels: bug

#1890 🐛(frontend) disable payment button if a product has no courses
  src/frontend/js/components/SaleTunnel/index.spec.tsx
  src/frontend/js/components/SaleTunnel/index.tsx
Labels: bug
