Repository openfun/richie, pull requests merged in 2023-10, with the labels that each got.

#2113 🧑‍💻(frontend) use enum for http status code
  src/frontend/js/api/joanie.spec.ts
  src/frontend/js/api/lms/openedx-hawthorn.spec.ts
  src/frontend/js/api/lms/openedx-hawthorn.ts
  src/frontend/js/components/Icon/index.stories.tsx
  src/frontend/js/components/PaymentButton/index.spec.tsx
  src/frontend/js/contexts/SessionContext/index.spec.tsx
  src/frontend/js/hooks/useDownloadCertificate/index.spec.tsx
  src/frontend/js/hooks/useResources/index.spec.tsx
  src/frontend/js/hooks/useUnionResource/index.spec.tsx
  src/frontend/js/hooks/useUnionResource/utils/fetchEntity.ts
  src/frontend/js/pages/DashboardAddressesManagement/DashboardCreateAddress.spec.tsx
  src/frontend/js/pages/DashboardAddressesManagement/DashboardEditAddress.spec.tsx
  src/frontend/js/pages/DashboardAddressesManagement/index.spec.tsx
  src/frontend/js/pages/DashboardCertificates/index.spec.tsx
  src/frontend/js/pages/DashboardCourses/index.spec.tsx
  src/frontend/js/pages/DashboardCreditCardsManagement/DashboardEditCreditCard.spec.tsx
  src/frontend/js/pages/DashboardCreditCardsManagement/index.spec.tsx
  src/frontend/js/utils/errors/HttpError.ts
  src/frontend/js/utils/react-query/useSessionMutation/index.spec.tsx
  src/frontend/js/utils/react-query/useSessionMutation/index.ts
  src/frontend/js/utils/react-query/useSessionQuery/index.spec.tsx
  src/frontend/js/utils/react-query/useSessionQuery/index.ts
  src/frontend/js/utils/search/getSuggestionsSection/index.spec.ts
  src/frontend/js/utils/search/getSuggestionsSection/index.ts
  src/frontend/js/utils/search/index.tsx
  src/frontend/js/widgets/Dashboard/components/DashboardItem/Certificate/index.spec.tsx
  src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/DashboardItemOrder.spec.tsx
  src/frontend/js/widgets/Search/index.spec.tsx
  src/frontend/js/widgets/Search/utils/getResourceList/index.spec.ts
  src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseProductItem/components/CourseProductCertificateItem/index.spec.tsx
  src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseProductItem/components/CourseProductCourseRuns/index.spec.tsx
  src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseProductItem/index.spec.tsx
  src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseRunEnrollment/index.joanie.spec.tsx
  src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseRunEnrollment/index.openedx.spec.tsx
  src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseWishButton/hooks/useCourseWish/index.spec.tsx
  src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseWishButton/index.login.spec.tsx
  src/frontend/js/widgets/SyllabusCourseRunsList/hooks/useCourseEnrollment/index.spec.tsx
  src/frontend/js/widgets/UserLogin/index.spec.tsx
Labels: improvement

#2082 ✨(frontend) add component for Order state message
  CHANGELOG.md
  src/frontend/js/types/Joanie.ts
  src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/DashboardItemOrder.tsx
  src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/OrderStateMessage/index.spec.tsx
  src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/OrderStateMessage/index.tsx
Labels: feature

#2099 📱(frontend) fix mobile dashboard layout
  CHANGELOG.md
  src/frontend/js/pages/TeacherDashboardCoursesLoader/index.spec.tsx
  src/frontend/js/widgets/Dashboard/components/DashboardLayout/_styles.scss
  src/frontend/js/widgets/Dashboard/components/DashboardSidebar/_styles.scss
  src/frontend/js/widgets/Dashboard/components/DashboardSidebar/components/NavigationSelect.tsx
  src/frontend/js/widgets/Dashboard/components/DashboardSidebar/index.tsx
  src/frontend/js/widgets/Dashboard/components/TeacherDashboardCourseSidebar/index.spec.tsx
  src/frontend/js/widgets/Dashboard/components/TeacherDashboardProfileSidebar/index.spec.tsx
  src/frontend/scss/objects/_course_glimpses.scss
Labels: improvement

#2115 🐛(frontend) prevent LTIConsumer context to be refreshed on user update
  CHANGELOG.md
  src/frontend/js/widgets/LtiConsumer/index.spec.tsx
  src/frontend/js/widgets/LtiConsumer/index.tsx
Labels: bug

#2124 🐛(frontend) OrderStateMessage handle error on "validated" state
  src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/OrderStateMessage/index.tsx
Labels: bug

#2127 🛂(backend) update default courses and organizations permissions
  CHANGELOG.md
  src/richie/apps/courses/defaults.py
Labels: bug
