Repository openfun/richie, pull requests merged in 2023-02, with the labels that each got.

#1893 💄(frontend) allow to customise course enrollment colors in subheader
  CHANGELOG.md
  UPGRADE.md
  src/frontend/js/components/CourseRunEnrollment/_styles.scss
  src/frontend/scss/colors/_theme.scss
Labels: improvement, a11y

#1910 🐛(courses) fix course runs sync api when course has a snapshot
  CHANGELOG.md
  src/richie/apps/courses/api.py
  tests/apps/courses/test_api_course_run_sync.py
Labels: bug

#1905 ✨(frontend) CourseRunEnrollment - CourseRun managed by Joanie
  CHANGELOG.md
  src/frontend/js/components/CourseRunEnrollment/_styles.scss
  src/frontend/js/components/CourseRunEnrollment/index.joanie.spec.tsx
  src/frontend/js/components/CourseRunEnrollment/index.openedx.spec.tsx
  src/frontend/js/components/CourseRunEnrollment/index.tsx
  src/frontend/js/data/useCourseEnrollment/index.ts
  src/frontend/js/types/api.ts
  src/frontend/js/utils/api/configuration.ts
  src/frontend/js/utils/api/enrollment.ts
  src/frontend/js/utils/api/joanie.ts
  src/frontend/js/utils/api/lms/index.ts
  src/frontend/js/utils/api/lms/joanie.ts
  src/frontend/js/utils/api/lms/openedx-hawthorn.ts
Labels: feature

#1909 ✨(frontend) EnrolledCourseRun button displayed when course is not yet opened
  CHANGELOG.md
  src/frontend/js/components/CourseProductCourseRuns/EnrolledCourseRun.tsx
  src/frontend/js/components/CourseProductCourseRuns/_styles.scss
  src/frontend/js/components/CourseProductCourseRuns/index.spec.tsx
  src/frontend/js/components/CourseProductItem/CourseRunItem.tsx
  src/frontend/js/components/CourseRunEnrollment/index.tsx
  src/frontend/js/components/CourseRunUnenrollmentButton/_styles.scss
  src/frontend/js/components/CourseRunUnenrollmentButton/index.spec.tsx
  src/frontend/js/components/CourseRunUnenrollmentButton/index.tsx
  src/frontend/js/utils/relativeDate.ts
  src/frontend/js/utils/useDateRelative.tsx
  src/frontend/scss/components/_index.scss
Labels: improvement

#1912 ✨(backend) implement feature flags from .env
  CHANGELOG.md
  env.d/development/dev-ssl.dist
  env.d/development/dev.dist
  sandbox/settings.py
  src/richie/apps/core/templatetags/feature_flags.py
  tests/apps/core/test_templatetags_feature_flags.py
Labels: feature

#1914 🐛(frontend) fix enrollment not started test for CourseProductCourseRuns
  src/frontend/js/components/CourseProductCourseRuns/index.spec.tsx
Labels: bug

#1915 💄(frontend) fix style bug on course glimpse when used in a section
  CHANGELOG.md
  src/frontend/scss/objects/_course_glimpses.scss
Labels: bug

#1904 ✨(frontend) user course wishlist
  CHANGELOG.md
  src/frontend/js/components/Button/index.tsx
  src/frontend/js/components/CourseAddToWishlist/_styles.scss
  src/frontend/js/components/CourseAddToWishlist/index.login.spec.tsx
  src/frontend/js/components/CourseAddToWishlist/index.logout.spec.tsx
  src/frontend/js/components/CourseAddToWishlist/index.tsx
  src/frontend/js/components/Root/index.tsx
  src/frontend/js/components/Spinner/index.tsx
  src/frontend/js/hooks/useResources/useResourcesRoot.ts
  src/frontend/js/hooks/useUserWishlistCourses/index.spec.tsx
  src/frontend/js/hooks/useUserWishlistCourses/index.ts
  src/frontend/js/types/Joanie.ts
  src/frontend/js/utils/api/joanie.ts
  src/frontend/js/utils/test/factories.ts
  src/frontend/scss/components/_index.scss
  src/richie/apps/courses/templates/courses/cms/course_detail.html
Labels: feature
