Repository openfun/richie, pull requests merged in 2023-12, with the labels that each got.

#2145 ✨(frontend) handle OrderGroup on product purchase
  CHANGELOG.md
  src/frontend/js/components/PaymentButton/index.spec.tsx
  src/frontend/js/components/PaymentButton/index.tsx
  src/frontend/js/components/PurchaseButton/index.tsx
  src/frontend/js/components/SaleTunnel/context.tsx
  src/frontend/js/components/SaleTunnel/index.tsx
  src/frontend/js/types/Joanie.ts
  src/frontend/js/utils/ProductHelper/index.ts
  src/frontend/js/utils/test/factories/joanie.ts
  src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseProductItem/_styles.scss
  src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseProductItem/index.spec.tsx
  src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseProductItem/index.tsx
Labels: feature

#2165 🐛(frontend) fix various cache order issues
  CHANGELOG.md
  src/frontend/js/hooks/useUnionResource/utils/fetchEntity.ts
  src/frontend/js/pages/DashboardCourses/useOrdersEnrollments.tsx
  src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/DashboardItemOrderContract.spec.tsx
Labels: bug

#2164 🐛(frontend) retrieve product certificate order
  src/frontend/js/components/PaymentButton/index.spec.tsx
  src/frontend/js/components/PaymentButton/index.tsx
  src/frontend/js/components/PurchaseButton/index.spec.tsx
  src/frontend/js/components/PurchaseButton/index.tsx
  src/frontend/js/components/SaleTunnel/components/SaleTunnelStepValidation/index.spec.tsx
  src/frontend/js/components/SaleTunnel/context.tsx
  src/frontend/js/components/SaleTunnel/index.tsx
  src/frontend/js/hooks/useProductOrder/index.tsx
  src/frontend/js/types/Joanie.ts
  src/frontend/js/utils/test/factories/joanie.ts
  src/frontend/js/widgets/Dashboard/components/DashboardItem/Enrollment/DashboardItemEnrollment.tsx
  src/frontend/js/widgets/Dashboard/components/DashboardItem/Enrollment/ProductCertificateFooter/index.spec.tsx
  src/frontend/js/widgets/Dashboard/components/DashboardItem/Enrollment/ProductCertificateFooter/index.tsx
  src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseProductItem/CourseProductItemFooter/index.tsx
  src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseProductItem/index.tsx
Labels: bug

#2170 🐛(frontend) multiple calls of pushBreadcrumbsPlaceholders
  src/frontend/js/hooks/useBreadcrumbsPlaceholders.tsx
Labels: bug

#2180 💄(frontend) fix organization logo link size issue
  src/frontend/js/widgets/Dashboard/components/TeacherDashboardProfileSidebar/components/OrganizationLinks/_styles.scss
  src/frontend/js/widgets/Dashboard/components/TeacherDashboardProfileSidebar/components/OrganizationLinks/index.tsx
Labels: bug

#2179 🩹(backend) properly set AUTHENTICATION_DELEGATION.PROFILE_URLS
  sandbox/settings.py
Labels: bug

#2167 💄(frontend) hide order sidebar, hide filters space
  src/frontend/js/pages/DashboardOrderLayout/_styles.scss
  src/frontend/js/pages/DashboardOrderLayout/index.tsx
  src/frontend/js/widgets/Dashboard/components/DashboardLayout/_styles.scss
  src/frontend/js/widgets/Dashboard/components/DashboardLayout/index.tsx
  src/frontend/scss/components/_index.scss
Labels: improvement

#2195 ✨(frontend) add ContractHelper to compute state
  src/frontend/js/components/ContractStatus/index.tsx
  src/frontend/js/types/Joanie.ts
  src/frontend/js/utils/ContractHelper/index.spec.ts
  src/frontend/js/utils/ContractHelper/index.ts
Labels: feature

#2199 🐛(frontend) Fix useUnionResource hasLoadMore
  src/frontend/js/hooks/useUnionResource/index.spec.tsx
  src/frontend/js/hooks/useUnionResource/index.ts
  src/frontend/js/pages/DashboardCourses/index.spec.tsx
Labels: improvement
