Repository openfun/richie, pull requests merged in 2023-07, with the labels that each got.

#2007 ✨(backend) change course glimpse footer state
  CHANGELOG.md
  src/frontend/js/pages/TeacherCourseDashboardLoader/CourseRunList/utils.tsx
  src/frontend/js/types/index.ts
  src/frontend/js/utils/test/factories/joanie.ts
  src/frontend/js/utils/test/factories/richie.ts
  src/richie/apps/courses/models/course.py
  tests/apps/courses/test_models_course_run.py
  tests/apps/search/test_query_courses.py
Labels: improvement

#2018 🐛(frontend) make remaining_order_count optional
  src/frontend/js/types/Joanie.ts
  src/frontend/js/widgets/CourseProductItem/components/PurchaseButton/index.spec.tsx
  src/frontend/js/widgets/CourseProductItem/components/PurchaseButton/index.tsx
Labels: bug

#1998 ✨(backend) add all available languages of courses and icons
  CHANGELOG.md
  src/frontend/scss/components/_subheader.scss
  src/frontend/scss/objects/_characteristics.scss
  src/richie/apps/core/fields/multiselect.py
  src/richie/apps/core/templates/richie/icons.html
  src/richie/apps/courses/models/course.py
  src/richie/apps/courses/templates/courses/cms/course_detail.html
  tests/apps/courses/test_models_course_run.py
  tests/apps/courses/test_templates_course_detail_rendering.py
Labels: feature

#2038 💚(crowdin) upgrade crowdin to version 3.13.0
  .circleci/config.yml
  docker-compose.yml
Labels: bug

#2040 🐛(frontend) fix organization breadcrumb
  src/frontend/js/pages/TeacherOrganizationCourseDashboardLoader/index.tsx
Labels: bug

#2045 ⬆️(deps) update js dependencies
  cookiecutter/{{cookiecutter.organization}}-richie-site-factory/template/{{cookiecutter.site}}/src/frontend/yarn.lock
  src/frontend/package.json
  src/frontend/yarn.lock
Labels: dependencies
