Repository openfun/richie, pull requests merged in 2024-02, with the labels that each got.

#2269 🐛(frontend) fix syllabus "Go to course" link
  CHANGELOG.md
  src/frontend/js/types/Joanie.ts
  src/frontend/js/types/index.ts
  src/frontend/js/utils/test/factories/joanie.ts
  src/frontend/js/widgets/Dashboard/components/DashboardItem/stories.mock.ts
  src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseRunEnrollment/index.joanie.spec.tsx
  src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseRunEnrollment/index.tsx
  src/frontend/js/widgets/SyllabusCourseRunsList/hooks/useCourseEnrollment/index.ts
Labels: critical, bug

#2261 🐛(frontend) fix teacher courses list scroll top
  CHANGELOG.md
  src/frontend/js/components/TeacherDashboardCourseList/index.tsx
Labels: bug

#2268 🐛(frontend) remove enrollment start on some course run
  CHANGELOG.md
  src/frontend/js/widgets/Dashboard/components/DashboardItem/DashboardItemCourseEnrolling.spec.tsx
  src/frontend/js/widgets/Dashboard/components/DashboardItem/DashboardItemCourseEnrolling.tsx
Labels: bug

#2280 ✅(frontend) fix flaky test
  CHANGELOG.md
  src/frontend/js/utils/CreditCardHelper/index.spec.tsx
  src/frontend/js/utils/CreditCardHelper/index.tsx
Labels: bug

#2287 🩹(frontend) prevent to clear address select field
  src/frontend/js/components/RegisteredAddress/index.tsx
  src/frontend/js/components/SaleTunnel/components/SaleTunnelStepPayment/index.spec.tsx
  src/frontend/js/components/SaleTunnel/components/SaleTunnelStepPayment/index.tsx
Labels: bug

#2286 ✨(frontend) require terms consent on all purchase
  CHANGELOG.md
  src/frontend/js/components/PaymentButton/index.spec.tsx
  src/frontend/js/components/PaymentButton/index.tsx
  src/frontend/js/types/Joanie.ts
Labels: feature
