Repository openfun/richie, pull requests merged in 2024-05, with the labels that each got.

#2399 🐛(back) fully define STORAGES settings
  cookiecutter/{{cookiecutter.organization}}-richie-site-factory/template/{{cookiecutter.site}}/src/backend/{{cookiecutter.site}}/settings.py
  sandbox/settings.py
Labels: bug, python

#2396 ⬆️(backend) upgrade to python 3.11
  .circleci/config.yml
  CHANGELOG.md
  Dockerfile
  cookiecutter/{{cookiecutter.organization}}-richie-site-factory/.circleci/src/jobs/@backend.yml
  cookiecutter/{{cookiecutter.organization}}-richie-site-factory/.circleci/src/jobs/@project.yml
  cookiecutter/{{cookiecutter.organization}}-richie-site-factory/Dockerfile
  pyproject.toml
  tests/apps/search/test_indexers_courses.py
Labels: dependencies, python

#2401 🐛(frontend) useUnionResource refetch
  CHANGELOG.md
  src/frontend/js/hooks/useUnionResource/index.spec.tsx
  src/frontend/js/hooks/useUnionResource/index.ts
  src/frontend/js/hooks/useUnionResource/utils/fetchEntity.ts
Labels: bug

#2407 💄(frontend) fix layout issue on DashboardItem
  CHANGELOG.md
  src/frontend/js/widgets/Dashboard/components/DashboardItem/_styles.scss
Labels: bug

#2411 🐛(frontend) use CB logo as fallback if credit card is unknown
  CHANGELOG.md
  src/frontend/js/pages/DashboardCreditCardsManagement/CreditCardBrandLogo.spec.tsx
  src/frontend/js/pages/DashboardCreditCardsManagement/CreditCardBrandLogo.tsx
  src/frontend/js/types/Joanie.ts
Labels: improvement
