Repository openfun/richie, pull requests merged in 2024-04, with the labels that each got.

#2333 🔍️(backend) complete course detail RDFa markups
  CHANGELOG.md
  src/richie/apps/courses/templates/courses/cms/course_detail.html
  src/richie/apps/courses/templates/courses/cms/fragment_category_glimpse.html
  src/richie/apps/courses/templates/courses/cms/fragment_organization_glimpse.html
  src/richie/apps/courses/templates/courses/cms/fragment_person_glimpse.html
  src/richie/apps/courses/templates/courses/plugins/licence_plugin.html
  src/richie/plugins/nesteditem/templates/richie/nesteditem/nesteditem.html
  tests/apps/courses/test_cms_plugins_organization.py
  tests/apps/courses/test_cms_plugins_person.py
  tests/apps/courses/test_licence_plugin.py
  tests/apps/courses/test_templates_course_detail_rdfa.py
  tests/apps/courses/test_templates_course_detail_rendering.py
  tests/apps/courses/test_templates_person_detail.py
Labels: improvement

#2340 ♻️(frontend) remove i18n routing
  CHANGELOG.md
  src/frontend/js/components/CourseGlimpse/utils.ts
  src/frontend/js/components/SaleTunnel/components/SaleTunnelStepResume/index.tsx
  src/frontend/js/components/SignContractButton/index.tsx
  src/frontend/js/pages/DashboardAddressesManagement/DashboardCreateAddress.spec.tsx
  src/frontend/js/pages/DashboardAddressesManagement/DashboardCreateAddressLoader.tsx
  src/frontend/js/pages/DashboardAddressesManagement/DashboardEditAddress.spec.tsx
  src/frontend/js/pages/DashboardAddressesManagement/DashboardEditAddressLoader.tsx
  src/frontend/js/pages/DashboardAddressesManagement/index.spec.tsx
  src/frontend/js/pages/DashboardCertificates/index.spec.tsx
  src/frontend/js/pages/DashboardContracts/index.spec.tsx
  src/frontend/js/pages/DashboardCourses/index.spec.tsx
  src/frontend/js/pages/DashboardCreditCardsManagement/DashboardEditCreditCard.spec.tsx
  src/frontend/js/pages/DashboardCreditCardsManagement/DashboardEditCreditCardLoader.tsx
  src/frontend/js/pages/DashboardCreditCardsManagement/index.spec.tsx
  src/frontend/js/pages/DashboardOrderLayout/index.spec.tsx
  src/frontend/js/pages/DashboardOrderLayout/index.tsx
  src/frontend/js/pages/DashboardPreferences/index.tsx
  src/frontend/js/widgets/Dashboard/components/DashboardItem/Enrollment/ProductCertificateFooter/index.spec.tsx
  src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/DashboardItemOrder.spec.tsx
  src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/DashboardItemOrder.tsx
  src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/DashboardItemOrderContract.spec.tsx
  src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/DashboardItemOrderContract.useUnionResource.cache.spec.tsx
  src/frontend/js/widgets/Dashboard/components/LearnerDashboardSidebar/index.tsx
  src/frontend/js/widgets/Dashboard/components/TeacherDashboardCourseSidebar/index.spec.tsx
  src/frontend/js/widgets/Dashboard/components/TeacherDashboardCourseSidebar/index.tsx
  src/frontend/js/widgets/Dashboard/components/TeacherDashboardCourseSidebar/utils.ts
  src/frontend/js/widgets/Dashboard/components/TeacherDashboardOrganizationSidebar/index.tsx
  src/frontend/js/widgets/Dashboard/components/TeacherDashboardProfileSidebar/components/OrganizationLinks/index.tsx
  src/frontend/js/widgets/Dashboard/components/TeacherDashboardProfileSidebar/index.spec.tsx
  src/frontend/js/widgets/Dashboard/components/TeacherDashboardProfileSidebar/index.tsx
  src/frontend/js/widgets/Dashboard/hooks/useDashboardRouter/index.tsx
  src/frontend/js/widgets/Dashboard/index.spec.tsx
  src/frontend/js/widgets/Dashboard/utils/dashboardRoutes.tsx
  src/frontend/js/widgets/Dashboard/utils/learnerRouteMessages.tsx
  src/frontend/js/widgets/Dashboard/utils/learnerRoutes.tsx
  src/frontend/js/widgets/Dashboard/utils/learnerRoutesPaths.tsx
  src/frontend/js/widgets/Dashboard/utils/teacherDashboardPaths.tsx
  src/frontend/js/widgets/Dashboard/utils/teacherRouteMessages.tsx
  src/frontend/js/widgets/Dashboard/utils/teacherRoutes.tsx
  src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseProductItem/components/ProductSignatureHeader/index.tsx
Labels: improvement

#2359 ✅ (frontend) fix false positive test
  src/frontend/js/components/PurchaseButton/index.spec.tsx
Labels: bug

#2360 💄(frontend) improve order group message color and layout
  src/frontend/js/components/PurchaseButton/index.tsx
  src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseProductItem/CourseProductItemFooter/index.tsx
  src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseProductItem/_styles.scss
Labels: improvement

#2377 🚑(template) fix duplicated placeholder in course detail template
  CHANGELOG.md
  src/richie/apps/courses/templates/courses/cms/course_detail.html
Labels: critical, bug

#2381 ✨(frontend) add page 404 not found
  CHANGELOG.md
  src/frontend/js/pages/DashboardPageNotFound/index.tsx
  src/frontend/js/widgets/Dashboard/components/DashboardLayout/index.tsx
  src/frontend/js/widgets/Dashboard/index.spec.tsx
  src/frontend/js/widgets/Dashboard/utils/dashboardRoutes.tsx
Labels: feature
