Repository openfun/richie, pull requests merged in 2024-08, with the labels that each got.

#2468 🐛(ci) fix npm development version
  .circleci/config.yml
  CHANGELOG.md
Labels: bug

#2472 ✏️(backend) fix type in url path regex
  CHANGELOG.md
  src/richie/apps/courses/urls.py
Labels: bug

#2476 🌐(all) update messages
  src/frontend/i18n/locales/ar-SA.json
  src/frontend/i18n/locales/es-ES.json
  src/frontend/i18n/locales/fa-IR.json
  src/frontend/i18n/locales/fr-CA.json
  src/frontend/i18n/locales/fr-FR.json
  src/frontend/i18n/locales/ko-KR.json
  src/frontend/i18n/locales/pt-PT.json
  src/frontend/i18n/locales/ru-RU.json
  src/frontend/i18n/locales/vi-VN.json
  src/frontend/js/translations/ar-SA.json
  src/frontend/js/translations/es-ES.json
  src/frontend/js/translations/fa-IR.json
  src/frontend/js/translations/fr-CA.json
  src/frontend/js/translations/fr-FR.json
  src/frontend/js/translations/ko-KR.json
  src/frontend/js/translations/pt-PT.json
  src/frontend/js/translations/ru-RU.json
  src/frontend/js/translations/vi-VN.json
  src/richie/locale/ar_SA/LC_MESSAGES/django.mo
  src/richie/locale/ar_SA/LC_MESSAGES/django.po
  src/richie/locale/es_ES/LC_MESSAGES/django.mo
  src/richie/locale/es_ES/LC_MESSAGES/django.po
  src/richie/locale/fr_CA/LC_MESSAGES/django.mo
  src/richie/locale/fr_CA/LC_MESSAGES/django.po
  src/richie/locale/fr_FR/LC_MESSAGES/django.mo
  src/richie/locale/fr_FR/LC_MESSAGES/django.po
  src/richie/locale/ko_KR/LC_MESSAGES/django.mo
  src/richie/locale/ko_KR/LC_MESSAGES/django.po
  src/richie/locale/pt_PT/LC_MESSAGES/django.mo
  src/richie/locale/pt_PT/LC_MESSAGES/django.po
  src/richie/locale/ru_RU/LC_MESSAGES/django.mo
  src/richie/locale/ru_RU/LC_MESSAGES/django.po
  src/richie/locale/vi_VN/LC_MESSAGES/django.mo
  src/richie/locale/vi_VN/LC_MESSAGES/django.po
Labels: FUN Team

#2479 👔(frontend) refresh credit cards query on payment method definition
  src/frontend/js/components/CreditCardSelector/index.tsx
  src/frontend/js/components/SaleTunnel/SaleTunnelSavePaymentMethod/index.tsx
  src/frontend/js/components/SaleTunnel/index.full-process.spec.tsx
  src/frontend/js/settings/settings.prod.ts
  src/frontend/js/settings/settings.test.ts
Labels: bug, improvement
