Repository openfun/richie, pull requests merged in 2024-01, with the labels that each got.

#2209 ⬆️(cookiecutter) migrate to node 18
  cookiecutter/{{cookiecutter.organization}}-richie-site-factory/.circleci/src/jobs/@frontend.yml
  cookiecutter/{{cookiecutter.organization}}-richie-site-factory/Dockerfile
  cookiecutter/{{cookiecutter.organization}}-richie-site-factory/docker-compose.yml
  cookiecutter/{{cookiecutter.organization}}-richie-site-factory/template/{{cookiecutter.site}}/src/frontend/package.json
Labels: dependencies

#2211 🩹(frontend) fix dashboard sidebar zindex issue
  src/frontend/js/widgets/Dashboard/components/DashboardSidebar/_styles.scss
Labels: bug

#2221 💄(frontend) reorder learner dashbaord menu link
  CHANGELOG.md
  src/frontend/js/widgets/Dashboard/components/LearnerDashboardSidebar/index.tsx
Labels: improvement

#2224 🩹(frontend) await logout request
  CHANGELOG.md
  src/frontend/js/contexts/SessionContext/BaseSessionProvider.tsx
  src/frontend/js/contexts/SessionContext/JoanieSessionProvider.tsx
Labels: bug

#2230 🐛(frontend) fix routes to redirect user to its dashboard
  CHANGELOG.md
  src/frontend/js/components/SaleTunnel/components/SaleTunnelStepResume/index.spec.tsx
  src/frontend/js/components/SaleTunnel/components/SaleTunnelStepResume/index.tsx
  src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseProductItem/components/ProductSignatureHeader/index.tsx
Labels: bug

#2234 Fix issue #2232
  CHANGELOG.md
  src/frontend/js/widgets/Dashboard/components/DashboardItem/DashboardItemCourseEnrolling.tsx
  src/frontend/js/widgets/Dashboard/components/DashboardItem/Enrollment/DashboardItemEnrollment.spec.tsx
  src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/DashboardItemOrder.spec.tsx
  src/frontend/js/widgets/Dashboard/components/DashboardItem/_styles.scss
Labels: improvement

#2250 🐛(frontend) Fix contract reload after signing
  src/frontend/js/components/ContractFrame/OrganizationContractFrame.spec.tsx
  src/frontend/js/components/ContractFrame/OrganizationContractFrame.tsx
Labels: bug

#2245 ✨(frontend) add signature polling description
  CHANGELOG.md
  src/frontend/js/components/ContractFrame/AbstractContractFrame.spec.tsx
  src/frontend/js/components/ContractFrame/AbstractContractFrame.tsx
Labels: improvement

#2259 🔧(back) configure renovate with pyproject file
  renovate.json
Labels: FUN Team, improvement

#2256 🐛(frontend) fix logout issue
  CHANGELOG.md
  src/frontend/js/api/lms/dummy.spec.ts
  src/frontend/js/api/lms/dummy.ts
  src/frontend/js/contexts/SessionContext/BaseSessionProvider.tsx
  src/frontend/js/contexts/SessionContext/JoanieSessionProvider.tsx
  src/frontend/js/contexts/SessionContext/index.spec.tsx
Labels: bug
